// Georgia Trip Master Plan — All Regions & Experiences
// Source: The MASTER PLAN document (Section 1 — THE MENU)

export const TRIP_INFO = {
  title: "Georgia Trip 2026",
  subtitle: "🇬🇪 The Master Plan",
  dates: "~8–20 August 2026",
  group: "8 people (5 adults + 3 kids under 18)",
  style: "Mid-range/value · Cool & comfortable · Light activity",
  currencyNote: "₾1 ≈ ₹36 ≈ AED 1.37 (late-June 2026 — reconfirm on the day)",
};

export const TAG_MAP = {
  cool: { emoji: "❄️", label: "Cool/Shaded", color: "#4A7C8F" },
  kids: { emoji: "🧒", label: "Kid-friendly", color: "#E8A87C" },
  wine: { emoji: "🍷", label: "Wine/Food", color: "#8B2252" },
  scenic: { emoji: "👀", label: "Scenic", color: "#6B8E23" },
  water: { emoji: "🚣", label: "On Water", color: "#3B82F6" },
  cave: { emoji: "🪨", label: "Cave/Canyon", color: "#8B7355" },
  walk: { emoji: "🚶", label: "Light Walk", color: "#9CAF88" },
  hike: { emoji: "🥾", label: "Longer Walk", color: "#7B6B4E" },
  thrill: { emoji: "🪂", label: "Thrill", color: "#E63946" },
  evening: { emoji: "🌙", label: "Evening/Lit-up", color: "#6C63FF" },
};

export const USERS = [
  { id: 1, name: "Aadit", emoji: "😎", is_adult: true },
  { id: 2, name: "Seema", emoji: "🌸", is_adult: true },
  { id: 3, name: "Saugat", emoji: "🧔", is_adult: true },
  { id: 4, name: "Sharvani", emoji: "✨", is_adult: true },
  { id: 5, name: "Shivani", emoji: "💜", is_adult: true },
  { id: 6, name: "Nandini", emoji: "🌻", is_adult: false },
  { id: 7, name: "Aadya", emoji: "🦋", is_adult: false },
  { id: 8, name: "Vyom", emoji: "🚀", is_adult: false },
];

export const REGIONS = [
  {
    id: "tbilisi",
    name: "Tbilisi",
    icon: "🏙️",
    subtitle: "City, views, culture",
    description:
      "Hot but dry at midday in August; lovely evenings. Plan = mornings + evenings out, pool/indoors midday. Almost everything is free.",
    groupPick:
      "Cable car + funicular (kids + sunset), one private sulfur room (adults), museum for a hot afternoon. Rest is free.",
    reviewSummary:
      'The cable car is rated a must-do for the views (note: the fortress interior is under renovation, but the trip up is still worth it). Mtatsminda is praised as the best city-lights/sunset spot — try the ponchiki donuts up top. The sulfur baths are called the "ultimate reset," though the scrub is intense and the baths aren\'t advised for pregnant women. Chronicles of Georgia is a quiet, dramatic, underrated favourite.',
  },
  {
    id: "mtskheta",
    name: "Mtskheta & The Drive North",
    icon: "⛪",
    subtitle: "Ancient capital & gentle adventure",
    description:
      "You pass here heading to the mountains — catch two UNESCO churches and the gentle water adventure in one northbound morning, no backtracking.",
    groupPick:
      "Gentle Aragvi raft (over-10s) + Zhinvali lake paddle (younger/nervous) + Ananuri, all on the drive up.",
    reviewSummary:
      "The Aragvi raft is repeatedly called thrilling-but-safe and great for families, with lovely scenery (and it mellows in late summer). The churches are beautiful but can fill with tour groups midday — go early.",
  },
  {
    id: "kakheti",
    name: "Kakheti",
    icon: "🍇",
    subtitle: "Wine country",
    description:
      "Birthplace of wine (8,000 yrs), home of buried-clay-pot qvevri. Hot lowland — taste late-morning/late-afternoon, cellars are your cool refuge. Bases: pretty Sighnaghi / bigger Telavi (best wines nearby). Family cellars need a call ahead.",
    groupPick:
      "Khareba cool tunnel (kid-friendly, mountain-cooled) + a view-lunch at Pheasant's Tears or a family cellar. Kids get juice + churchkhela.",
    reviewSummary:
      'Visitors rave about the family-cellar hospitality — warm hosts, personal tours, "Georgian hospitality at its best," often with Caucasus/vineyard views. Pheasant\'s Tears is a natural-wine pilgrimage with a top restaurant next door. A few note the big-name wineries feel more commercial and rushed than the small maranis.',
  },
  {
    id: "gudauri-kazbegi",
    name: "Gudauri & Kazbegi",
    icon: "🏔️",
    subtitle: "Alpine, cool, glaciers (Marco Polo base)",
    description:
      "Your coolest, happiest zone. Mostly free nature; you pay for the 4×4 and thrill add-ons.",
    groupPick:
      "4×4 to Gergeti (all), easy Gveleti stroll, Friendship panorama — cool & light. Hiker adds Juta/Truso; the brave one does paragliding.",
    reviewSummary:
      'Gergeti is called the "crown jewel of any trip" — majestic setting under Mt Kazbek (it\'s about the setting more than the church interior); the 4×4 road is rough but quick, vs a steep ~1–1.5 hr hike. Paragliding is a repeated "must-do," with travelers stressing how safe and professional it felt and how breathtaking the views are — but it\'s weather-dependent (can cancel), so keep it flexible, bring cash, and pick an experienced operator.',
  },
  {
    id: "borjomi",
    name: "Borjomi & Bakuriani",
    icon: "🌿",
    subtitle: "Cool spa mountains (the Batumi swap)",
    description:
      "Forested, cooler than Tbilisi, kid-pleasing mineral-water park. Cheap throughout.",
    groupPick:
      "Borjomi Central Park (taste the water, rides, cable car) — easy, cheap, cool, very family-friendly. Add the gentle Mtkvari raft for a splash.",
    reviewSummary:
      'Families love the park for a relaxed half-day; the mineral water from the spring is famously salty/odd-tasting (kids find it funny). The setting is green and calm — a genuine break from the heat.',
  },
  {
    id: "kutaisi-imereti",
    name: "Kutaisi & Imereti",
    icon: "🌊",
    subtitle: "Caves, canyons & water (the western leg)",
    description:
      'The best "fun adventure in pretty places without the heat." Caves stay cool, canyons are shaded & turquoise, mostly built paths. This is west — opposite direction from Kazbegi, so it means a bigger loop. Canyons/caves often close Mondays; Okatse closes in rain (Sataplia is the backup).',
    groupPick:
      "Martvili boat + Prometheus cave — cool, shaded, both have a boat, thrill the kids, barely any walking. Add Okatse's walkway only if everyone's up for the ~2.5 km stroll (hiker's treat).",
    reviewSummary:
      'Prometheus is called one of the most impressive stalactite caves people have seen (classical music inside; some find the optional boat short). Okatse\'s hanging walkway gets "Indiana Jones / breathtaking" reactions. Martvili\'s turquoise water is beautiful, though a few feel it\'s over-commercialised and the boat is short. Common tip: all three in one day needs a driver/logistics — hard to self-do.',
  },
  {
    id: "uplistsikhe",
    name: "Uplistsikhe",
    icon: "🪨",
    subtitle: "Rock-hewn cave city (en route west, near Gori)",
    description:
      "Ancient city carved into the cliff — tunnels, passages, pagan altars. On the road toward Kutaisi, so it pairs with the western leg.",
    groupPick: null,
    reviewSummary:
      "Kids love clambering through the tunnels and it's genuinely atmospheric/ancient — but it's exposed and hot at midday, so bring water, hats, and go earlier.",
  },
];

export const EXPERIENCES = [
  // ========== TBILISI ==========
  {
    id: "tbilisi-old-town",
    regionId: "tbilisi",
    name: "Old Town Wander",
    description: "Lanes, balconies, café streets",
    time: "2–3 hr",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["evening", "walk"],
  },
  {
    id: "tbilisi-bridge-rike",
    regionId: "tbilisi",
    name: "Bridge of Peace + Rike Park",
    description: "LED footbridge + riverside park",
    time: "30–60 min",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["evening", "scenic", "kids"],
  },
  {
    id: "tbilisi-narikala",
    regionId: "tbilisi",
    name: "Narikala Cable Car + Fortress",
    description: "2-min ride up + walls/views",
    time: "45 min",
    priceLari: "2.5/ride",
    priceRupee: "₹90",
    priceAED: "AED 3",
    tags: ["scenic", "kids"],
  },
  {
    id: "tbilisi-mtatsminda",
    regionId: "tbilisi",
    name: "Mtatsminda Funicular + Park",
    description: "Cliff train + hilltop rides/sunset",
    time: "2–3 hr",
    priceLari: "~6–8 (+rides)",
    priceRupee: "₹216–288",
    priceAED: "AED 8–11",
    tags: ["kids", "evening", "scenic"],
  },
  {
    id: "tbilisi-sulfur-baths",
    regionId: "tbilisi",
    name: "Sulfur Baths (private room)",
    description: "Soak in the historic domes (per room/hr)",
    time: "~1 hr",
    priceLari: "50–150",
    priceRupee: "₹1,800–5,400",
    priceAED: "AED 68–205",
    tags: ["cool"],
  },
  {
    id: "tbilisi-sulfur-scrub",
    regionId: "tbilisi",
    name: 'Sulfur Scrub ("kisa")',
    description: "Traditional exfoliating scrub",
    time: "20 min",
    priceLari: "20–50",
    priceRupee: "₹720–1,800",
    priceAED: "AED 27–68",
    tags: [],
  },
  {
    id: "tbilisi-museum",
    regionId: "tbilisi",
    name: "Georgian National Museum",
    description: "A/C; gold Treasury highlight",
    time: "1–2 hr",
    priceLari: "20–30",
    priceRupee: "₹720–1,080",
    priceAED: "AED 27–41",
    tags: ["cool"],
  },
  {
    id: "tbilisi-chronicles",
    regionId: "tbilisi",
    name: "Chronicles of Georgia",
    description: "Giant carved pillars",
    time: "30–45 min",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic"],
  },
  {
    id: "tbilisi-churches",
    regionId: "tbilisi",
    name: "Churches (Sameba, Metekhi, Sioni)",
    description: "Cathedrals & old sites",
    time: "20–40 min ea",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic"],
  },
  {
    id: "tbilisi-dry-bridge",
    regionId: "tbilisi",
    name: "Dry Bridge Market / Fabrika",
    description: "Flea market / old-factory hangout",
    time: "30–60 min",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["evening"],
  },

  // ========== MTSKHETA & DRIVE NORTH ==========
  {
    id: "mtskheta-jvari",
    regionId: "mtskheta",
    name: "Jvari Monastery",
    description: "Hilltop church + valley viewpoint",
    time: "20–30 min",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic"],
  },
  {
    id: "mtskheta-svetitskhoveli",
    regionId: "mtskheta",
    name: "Svetitskhoveli Cathedral",
    description: "UNESCO cathedral",
    time: "30–45 min",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic"],
  },
  {
    id: "mtskheta-aragvi-raft",
    regionId: "mtskheta",
    name: "Aragvi Rafting (half-day)",
    description:
      "Easy grade 2–3 float (gentle in Aug); gear+guide",
    time: "1.5–2 hr on water",
    priceLari: "120–180",
    priceRupee: "₹4,320–6,480",
    priceAED: "AED 164–247",
    tags: ["water", "kids", "scenic"],
  },
  {
    id: "mtskheta-zhinvali-kayak",
    regionId: "mtskheta",
    name: "Zhinvali Kayak/Canoe",
    description: "Calm emerald-lake paddle, swimmable",
    time: "~2 hr",
    priceLari: "~40–50",
    priceRupee: "₹1,440–1,800",
    priceAED: "AED 55–68",
    tags: ["water", "kids", "cool"],
  },
  {
    id: "mtskheta-ananuri",
    regionId: "mtskheta",
    name: 'Ananuri Castle + "I ❤️ Georgia"',
    description: "Lakeside fortress + photo stop",
    time: "30–40 min",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic"],
  },

  // ========== KAKHETI ==========
  {
    id: "kakheti-winery-tasting",
    regionId: "kakheti",
    name: "Winery Tasting",
    description: "A flight at a family cellar",
    time: "1–1.5 hr",
    priceLari: "6–25",
    priceRupee: "₹216–900",
    priceAED: "AED 8–34",
    tags: ["wine"],
  },
  {
    id: "kakheti-khareba",
    regionId: "kakheti",
    name: 'Khareba "Wine Tunnel"',
    description: "Taste inside a cool hillside cave",
    time: "~1 hr",
    priceLari: "~20",
    priceRupee: "₹720",
    priceAED: "AED 27",
    tags: ["cool", "wine", "kids"],
  },
  {
    id: "kakheti-tsinandali",
    regionId: "kakheti",
    name: "Tsinandali Estate",
    description: "Historic manor, gardens, cellar",
    time: "1–2 hr",
    priceLari: "10–35",
    priceRupee: "₹360–1,260",
    priceAED: "AED 14–48",
    tags: ["wine", "scenic", "kids"],
  },
  {
    id: "kakheti-supra",
    regionId: "kakheti",
    name: "Winery Lunch / Supra",
    description: "Big traditional feast w/ wine",
    time: "1.5–2 hr",
    priceLari: "~30–60",
    priceRupee: "₹1,080–2,160",
    priceAED: "AED 41–82",
    tags: ["wine", "kids"],
  },
  {
    id: "kakheti-sighnaghi",
    regionId: "kakheti",
    name: "Sighnaghi Walls + Bodbe",
    description: "Ramparts walk + cypress convent",
    time: "1–2 hr",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic", "walk"],
  },

  // ========== GUDAURI & KAZBEGI ==========
  {
    id: "kazbegi-friendship",
    regionId: "gudauri-kazbegi",
    name: "Friendship of Nations Panorama",
    description: "Mosaic balcony over the valley",
    time: "20–30 min",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic", "walk", "kids"],
  },
  {
    id: "kazbegi-gergeti",
    regionId: "gudauri-kazbegi",
    name: "Gergeti Trinity by 4×4",
    description: "4×4 up (~20 min) + church/views",
    time: "half-day",
    priceLari: "~50–70 (per veh ~50)",
    priceRupee: "₹1,800–2,520",
    priceAED: "AED 68–96",
    tags: ["scenic", "walk"],
  },
  {
    id: "kazbegi-gveleti",
    regionId: "gudauri-kazbegi",
    name: "Gveleti Waterfall",
    description: "Easy walk to a falls",
    time: "1–1.5 hr",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["cool", "walk", "kids"],
  },
  {
    id: "kazbegi-juta-truso",
    regionId: "gudauri-kazbegi",
    name: "Juta / Truso Valley",
    description: "Green alpine valleys, flat lower bits",
    time: "half–full day",
    priceLari: "Free (4×4 extra)",
    priceRupee: "—",
    priceAED: "—",
    tags: ["cool", "hike", "scenic"],
  },
  {
    id: "kazbegi-paragliding",
    regionId: "gudauri-kazbegi",
    name: "Gudauri Paragliding (tandem)",
    description: "Float over the valley w/ instructor",
    time: "flight 10–30 min",
    priceLari: "~350–500",
    priceRupee: "₹12,600–18,000",
    priceAED: "AED 480–685",
    tags: ["thrill", "scenic"],
  },

  // ========== BORJOMI & BAKURIANI ==========
  {
    id: "borjomi-park",
    regionId: "borjomi",
    name: "Borjomi Central Park",
    description: "Mineral spring + playground + rides",
    time: "2–3 hr",
    priceLari: "~2–5 (+rides)",
    priceRupee: "₹70–180",
    priceAED: "AED 3–7",
    tags: ["kids", "cool"],
  },
  {
    id: "borjomi-cable-car",
    regionId: "borjomi",
    name: "Park Cable Car",
    description: "Up to a forest plateau",
    time: "5 min + time",
    priceLari: "~2",
    priceRupee: "₹70",
    priceAED: "AED 3",
    tags: ["scenic", "cool"],
  },
  {
    id: "borjomi-raft",
    regionId: "borjomi",
    name: "Mtkvari Family Rafting",
    description: "Short 8 km grade-2 float",
    time: "~1 hr",
    priceLari: "from ~80",
    priceRupee: "₹2,880",
    priceAED: "AED 110",
    tags: ["water", "kids", "cool"],
  },
  {
    id: "borjomi-np",
    regionId: "borjomi",
    name: "Borjomi-Kharagauli NP",
    description: "Forested reserve, easy trails",
    time: "half day",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["cool", "hike"],
  },

  // ========== KUTAISI & IMERETI ==========
  {
    id: "imereti-martvili",
    regionId: "kutaisi-imereti",
    name: "Martvili Canyon",
    description: "Boat through turquoise gorge + 700 m loop",
    time: "1–1.5 hr",
    priceLari: "~20 (+boat)",
    priceRupee: "₹720",
    priceAED: "AED 27",
    tags: ["water", "cave", "kids", "scenic"],
  },
  {
    id: "imereti-martvili-zip",
    regionId: "kutaisi-imereti",
    name: "Martvili Zipline",
    description: "Optional zip over the canyon",
    time: "15 min",
    priceLari: "~60",
    priceRupee: "₹2,160",
    priceAED: "AED 82",
    tags: ["thrill"],
  },
  {
    id: "imereti-prometheus",
    regionId: "kutaisi-imereti",
    name: "Prometheus Cave",
    description: "1.4 km lit stalactite halls + optional boat",
    time: "1–2 hr",
    priceLari: "40 (+boat 30)",
    priceRupee: "₹1,440 (+₹1,080)",
    priceAED: "AED 55 (+41)",
    tags: ["cool", "cave", "kids", "scenic"],
  },
  {
    id: "imereti-okatse",
    regionId: "kutaisi-imereti",
    name: "Okatse Canyon",
    description: "780–900 m cliff hanging-walkway",
    time: "2–3 hr (incl 2.5 km walk)",
    priceLari: "~30 (+4×4 15)",
    priceRupee: "₹1,080",
    priceAED: "AED 41",
    tags: ["scenic", "cave", "hike"],
  },
  {
    id: "imereti-sataplia",
    regionId: "kutaisi-imereti",
    name: "Sataplia Reserve",
    description: "Dinosaur footprints + glass platform",
    time: "1–1.5 hr",
    priceLari: "~20",
    priceRupee: "₹720",
    priceAED: "AED 27",
    tags: ["kids", "scenic"],
  },
  {
    id: "imereti-gelati-bagrati",
    regionId: "kutaisi-imereti",
    name: "Gelati / Bagrati",
    description: "UNESCO mosaics / hilltop cathedral",
    time: "30–45 min ea",
    priceLari: "Free",
    priceRupee: "—",
    priceAED: "—",
    tags: ["scenic"],
  },

  // ========== UPLISTSIKHE ==========
  {
    id: "uplistsikhe-cave",
    regionId: "uplistsikhe",
    name: "Uplistsikhe Cave Town",
    description: "Explore carved city, tunnels, altars",
    time: "1–1.5 hr",
    priceLari: "~15–25",
    priceRupee: "₹540–900",
    priceAED: "AED 21–34",
    tags: ["kids", "cave", "scenic"],
  },
  {
    id: "uplistsikhe-gori",
    regionId: "uplistsikhe",
    name: "Gori / Stalin Museum",
    description: "History stop nearby (optional)",
    time: "1–1.5 hr",
    priceLari: "~15–25",
    priceRupee: "₹540–900",
    priceAED: "AED 21–34",
    tags: [],
  },
];

// Locked plan / Section 2 content
export const LOCKED_PLAN = {
  title: "SECTION 2 — ALREADY LOCKED",
  subtitle: "Decisions made so far: Tbilisi base + day-by-day, route calls",
  note: "This section is read-only. These are the decisions already confirmed by the group.",
  days: [
    {
      day: "Day 1 (Aug 8)",
      title: "Arrival in Tbilisi",
      items: [
        "Arrive & settle into accommodation",
        "Evening: Old Town wander + Bridge of Peace (lit up at night)",
        "Dinner in the old town — try khinkali & khachapuri",
      ],
    },
    {
      day: "Day 2 (Aug 9)",
      title: "Tbilisi City Day",
      items: [
        "Morning: Narikala cable car + fortress views",
        "Midday: Georgian National Museum (A/C escape)",
        "Afternoon: Pool / rest",
        "Evening: Mtatsminda funicular for sunset + ponchiki donuts",
      ],
    },
    {
      day: "Day 3 (Aug 10)",
      title: "Tbilisi — Baths & Culture",
      items: [
        "Morning: Churches walk (Sameba, Metekhi, Sioni)",
        "Late morning: Sulfur baths — private room for adults",
        "Afternoon: Dry Bridge flea market + Fabrika",
        "Evening: Chronicles of Georgia (dramatic at golden hour)",
      ],
    },
    {
      day: "Day 4 (Aug 11)",
      title: "Drive North — Mtskheta → Gudauri",
      items: [
        "Morning: Jvari Monastery + Svetitskhoveli Cathedral",
        "Mid-morning: Aragvi rafting / Zhinvali kayak",
        "Lunch stop: Ananuri Castle + I ❤️ Georgia photo",
        "Afternoon: Arrive Gudauri / Kazbegi — settle in",
      ],
    },
    {
      day: "Day 5 (Aug 12)",
      title: "Kazbegi — The Crown Jewel",
      items: [
        "Morning: 4×4 to Gergeti Trinity Church",
        "Midday: Gveleti Waterfall easy stroll",
        "Afternoon: Friendship of Nations panorama",
        "Optional: Paragliding for the brave (weather permitting)",
      ],
    },
    {
      day: "Day 6 (Aug 13)",
      title: "Kazbegi Day 2 / Return",
      items: [
        "Morning: Juta or Truso Valley (hiker option) OR relax",
        "Afternoon: Drive back to Tbilisi",
        "Evening: Free evening in Tbilisi",
      ],
    },
    {
      day: "Day 7 (Aug 14)",
      title: "Kakheti — Wine Country",
      items: [
        "Morning: Drive to Kakheti",
        'Late morning: Khareba Wine Tunnel (cool, kid-friendly)',
        "Lunch: Supra feast at Pheasant's Tears or family cellar",
        "Afternoon: Tsinandali Estate gardens",
        "Evening: Sighnaghi walls sunset + Bodbe Convent",
      ],
    },
    {
      day: "Day 8 (Aug 15)",
      title: "TBD — Group Vote Decides",
      items: [
        "Option A: Borjomi & Bakuriani (cool spa mountains)",
        "Option B: Kutaisi & Imereti (caves, canyons, water)",
        "Option C: Rest day in Tbilisi",
        "→ Use this app to vote!",
      ],
    },
    {
      day: "Day 9 (Aug 16)",
      title: "TBD — Group Vote Decides",
      items: [
        "Continues from Day 8 choice",
        "If Kutaisi route: Uplistsikhe on the way",
        "→ Use this app to vote!",
      ],
    },
    {
      day: "Day 10 (Aug 17)",
      title: "TBD — Group Vote Decides",
      items: [
        "Flexible day based on group energy",
        "Option: Continue western leg / Return to Tbilisi",
        "→ Use this app to vote!",
      ],
    },
    {
      day: "Day 11 (Aug 18)",
      title: "Return to Tbilisi / Free Day",
      items: [
        "Morning: Last-minute sightseeing or shopping",
        "Afternoon: Rest & pack",
        "Evening: Farewell dinner",
      ],
    },
    {
      day: "Day 12 (Aug 19)",
      title: "Buffer / Departure Prep",
      items: [
        "Flexible — overflow activities or rest",
        "Last shopping / souvenirs",
        "Evening packing",
      ],
    },
    {
      day: "Day 13 (Aug 20)",
      title: "Departure",
      items: [
        "Check out & head to airport",
        "Safe travels! 🇬🇪✈️",
      ],
    },
  ],
};
