-- Migration 10 — Georgia catalog places: Gudauri & Kazbegi
--
-- GENERATED FILE. Source of truth is content/catalog/gudauri-kazbegi.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Alpine, cool, glaciers',
  summary       = 'The Georgian Military Highway climbs over the 2,379m Jvari Pass into Georgia''s high Caucasus, pairing the Gudauri ski plateau with Stepantsminda (still widely called Kazbegi) under the glaciers of Mount Kazbek. The hilltop Gergeti Trinity Church is the postcard, but the region also holds a ghost valley of mineral springs, a dead-end alpine hiking village, and the last stretch of road before Russia. It''s the coolest, greenest part of any Georgia itinerary — and the most weather-dependent.',
  when_to_go    = 'Summer (June-September) is when everything is open: Truso and Juta valleys are only accessible roughly late May through October, and the high passes are least likely to close. Mornings give the best odds of a cloud-free Kazbek — the peak is wrapped in cloud more often than not by early afternoon, even in July. Winter (December-March) turns Gudauri into a proper ski resort but makes Kazbegi sightseeing weather-dependent and occasionally impossible: the Jvari Pass has closed repeatedly in recent winters for avalanches and heavy snow, sometimes for days at a stretch. Whatever the season, build a spare half-day into the itinerary rather than scheduling the pass crossing as your last commitment before a flight.',
  getting_there = 'From Tbilisi, the Georgian Military Highway (E117) reaches Gudauri in about 2 hours (120 km) and Stepantsminda in about 2.5-3 hours (157 km) — paved and generally good, but it climbs over the 2,379m Jvari Pass, which is the region''s real bottleneck. The pass has recorded multiple full and partial closures in 2026 alone (avalanche closures in January, heavy-snow closures in February-March), and can also see avalanche-gate delays and truck queues even when technically open, mainly driven by traffic for Verkhny Lars/Dariali — the only Georgia-Russia land border crossing, a few kilometres past Stepantsminda. Check pass status the morning you travel. Marshrutkas run from Tbilisi''s Didube station to Kazbegi (roughly 3 hours, a few GEL); getting between Gudauri and the smaller Kazbegi sights without a car is difficult, so most visitors drive, hire a taxi, or book a tour.',
  base_towns    = 'Stepantsminda (Kazbegi) is the practical base for most of this list — walking distance to the Gergeti 4x4 pickup point, with the widest range of guesthouses and the Rooms Hotel. Gudauri, about 40 minutes south over the pass, is the resort base and makes most sense in ski season or if paragliding is the priority. Splitting a couple of nights between both suits a fuller itinerary.'
WHERE id = 'gudauri-kazbegi';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('gudauri-kazbegi-gergeti-trinity', 'gudauri-kazbegi', 'Gergeti Trinity Church', 'Georgia''s most photographed church, perched alone on a ridge under Mount Kazbek — not in the town below it.', 'This 14th-century Holy Trinity Church stands alone on a ridge at 2,170m above Stepantsminda, its cross-cupola silhouette set against Kazbek''s glaciers when the cloud lifts. Most visitors reach it by shared 4x4 from the town''s main square (about 20 minutes each way on a rough but graded track); the alternative is a steep 1.5-2 hour hike. The chapel interior is small and plain — the setting, not the architecture, is the reason to come. Kazbek itself is cloud-wrapped more often than not, so mornings give the best odds of a clear view.', 'The 4x4 track starts from Stepantsminda''s main square; drivers usually wait for a full jeep (4-6 people) before leaving. Expect roughly ₾15-30 per person for a shared round trip, or ₾70-100 to charter the whole vehicle. Cover shoulders and knees for the church. Kazbek is frequently in cloud by midday, whatever the forecast said that morning.', 'Early morning, before cloud builds over Kazbek', 90, '1.5 hr', 15, 30, '₾15-30 per person shared 4x4 (charter ~₾70-100)', 'Stepantsminda', 42.6624, 44.6205, 'The 4x4 ride up is half the fun for kids; hold on tight on the rough track. The steep hiking alternative isn''t realistic with small children.', false, ARRAY['scenic', 'walk']::TEXT[], 1, NULL, NULL),
  ('gudauri-kazbegi-stepantsminda-wander', 'gudauri-kazbegi', 'Stepantsminda Town Wander', 'The alpine base town itself — Terek riverside, guesthouse cafes, and your first look up at Kazbek.', 'Stepantsminda (most drivers and maps still say Kazbegi) is a small grid of streets along the Terek River at 1,740m, with guesthouses, a handful of cafes, and a main square where 4x4 drivers gather for the Gergeti run. It isn''t a sight so much as the region''s hub — worth half an hour to get oriented, change money, and look up at Kazbek framed between buildings on a clear day. It also makes a reasonable place to wait out weather before deciding on the pass or a 4x4 trip.', 'ATMs and a few grocery shops line the main street; card acceptance is patchy elsewhere in the region, so stock up on cash here before heading to Gergeti, Truso, or Juta.', NULL, 45, '45 min', NULL, NULL, 'Free', 'Stepantsminda', 42.6575, 44.64528, 'Flat, easy streets with a couple of playgrounds near the square.', false, ARRAY['walk']::TEXT[], 2, NULL, NULL),
  ('gudauri-kazbegi-gveleti-waterfall', 'gudauri-kazbegi', 'Gveleti Waterfall Hike', 'A shaded riverside walk to twin waterfalls near the Russian border, cooler than anything in town.', 'From a parking area on the Dariali side road, a marked trail follows the Gveleti stream through forest to the Small Gveleti Waterfall (20-30 easy minutes), with the 25m Big Gveleti Waterfall another steeper 45-60 minutes beyond it, over rougher ground with some scrambling and a cable handhold section. It''s one of the few genuinely shaded, cool walks in the region — a good match for a hot afternoon between more exposed stops. The water is glacial-cold and fast year-round.', 'Roadside parking costs around ₾5; the track beyond it is unpaved and rough, so leave a rental car there rather than driving further in. The final stretch up to the Big Waterfall is steep and can be slippery — wear real shoes, not sandals.', 'Midday, for the cool of the canyon', 120, '2 hr', NULL, NULL, 'Free', 'Gveleti', 42.70722, 44.62361, 'The lower Small Waterfall is an easy family walk; save the scrambly upper path for kids who hike confidently.', false, ARRAY['cool', 'walk', 'water']::TEXT[], 3, NULL, NULL),
  ('gudauri-kazbegi-sno-stone-heads', 'gudauri-kazbegi', 'Sno Village Stone Heads', 'Six giant granite heads of Georgian writers and heroes, carved into a roadside meadow.', 'A short detour off the Sno road, local sculptor Merab Piranishvili carved six monumental heads — Rustaveli, Chavchavadze, Tsereteli, Vazha-Pshavela, Alexander Kazbegi, and Christ — each from a single block of granite, set in an open meadow with the Sno valley peaks behind. It''s an easy, quick, slightly surreal stop that breaks up the drive to or from Juta or the horse-riding stables, and needs no more than a short stroll among the sculptures.', 'No fee and no fences — just pull off the road. Best light is late afternoon, when the low sun catches the carved faces.', 'Late afternoon', 20, '20 min', NULL, NULL, 'Free', 'Sno', 42.608209, 44.630906, 'Kids enjoy posing near (not on) the giant heads for photos.', false, ARRAY['scenic', 'kids']::TEXT[], 4, NULL, NULL),
  ('gudauri-kazbegi-friendship-monument', 'gudauri-kazbegi', 'Russia-Georgia Friendship Monument', 'A Soviet-era mosaic rotunda on the Jvari Pass with the best roadside panorama on the whole highway.', 'Built in 1983 to mark 200 years of the Treaty of Georgievsk, this circular mosaic-clad monument sits directly on the Georgian Military Highway between Gudauri and the 2,379m Jvari Pass, framing an enormous view down the Devil''s Valley toward the Khevi mountains. The mosaics lining the inside depict Georgian and Russian historical scenes. It''s a five-minute stop built into almost every Kazbegi drive, but worth actually getting out of the car for rather than just slowing down.', 'Roadside pull-off with vendor stalls selling honey, churchkhela, and knitwear — a convenient snack or bathroom break in either direction. Exposed and often windy, even in summer.', NULL, 20, '20 min', NULL, NULL, 'Free', 'Gudauri', 42.492, 44.4527, 'Easy, flat viewing area, but there are low walls kids like to climb — supervise near the edge.', false, ARRAY['scenic']::TEXT[], 5, NULL, NULL),
  ('gudauri-kazbegi-truso-valley', 'gudauri-kazbegi', 'Truso Valley', 'Ghost Ossetian villages and orange mineral-spring terraces, in a valley most day-trippers never turn off for.', 'West of the highway at Kobi, a rough 4x4 track climbs the Terek''s tributary into Truso Gorge, past travertine terraces stained white and orange by iron-rich mineral springs, ruined medieval watchtowers, and the abandoned village of Ketrisi. Guided 4x4 trips or hikes continue toward the ruined Zakagori fortress; beyond it, a free border-zone permit (checked on the spot by the military post, roughly a 30-minute process) is required, since the valley runs along the administrative boundary with South Ossetia. Most Kazbegi visitors never make the detour, which is much of the appeal.', 'The road is only reliably open roughly late May-October, closed by snow or mud outside that window. Local drivers from Stepantsminda''s main square typically charge ₾40-60 one-way or ₾80-100 return for the 4x4 leg; guided day tours cost more. Stay on the marked track — red-and-white boundary posts mark the actual border and must not be crossed.', 'Late morning, once the border post is staffed', 300, '5 hr', 40, 100, '₾40-100 for the 4x4 leg (per vehicle, negotiate)', 'Kobi', 42.583217, 44.427433, 'A long day on a rough, bumpy track — better suited to older kids than toddlers.', false, ARRAY['scenic', 'hike']::TEXT[], 6, NULL, NULL),
  ('gudauri-kazbegi-dariali-monastery', 'gudauri-kazbegi', 'Dariali Monastery Complex', 'A striking monastery built to look medieval, a few hundred meters from Georgia''s last checkpoint before Russia.', 'Consecrated in 2011 but modelled on the 11th-century Nikortsminda church, the Archangels Michael and Gabriel complex sits in the narrow Dariali Gorge, its hewn pinkish-grey stone, mosaics, and metalwork largely made by the resident monks themselves. It''s the last real stop before the highway reaches the Verkhny Lars/Dariali border post with Russia, so most self-drivers focused on the crossing ahead blow straight past it. Free to enter, quiet, and a striking contrast to Gergeti''s crowds a few kilometres south.', 'This is a working monastery right up against a sensitive border zone — dress modestly, stay within the complex, and don''t photograph the border infrastructure just beyond it. No entrance fee.', NULL, 30, '30 min', NULL, NULL, 'Free', 'Stepantsminda', 42.73554, 44.6314, NULL, false, ARRAY['scenic']::TEXT[], 7, NULL, NULL),
  ('gudauri-kazbegi-juta-chaukhi', 'gudauri-kazbegi', 'Juta Village & Chaukhi Valley', 'A dead-end alpine village under the jagged Chaukhi massif, and the trailhead for one of Georgia''s best day hikes.', 'A rough side road climbs about 12km from Sno to Juta, a scatter of guesthouses at 2,200m under the serrated Chaukhi massif (3,842m), sometimes nicknamed the Georgian Dolomites. From the village, a well-marked trail follows the Chaukhistskali river up the valley toward a small lake and glacier views, walkable as an out-and-back of almost any length depending on stamina. The Fifth Season guesthouse just outside the village is the usual last-food stop before the trail proper. This is the pick for travelers who want one real mountain hike rather than a string of roadside viewpoints.', 'The access road needs a high-clearance vehicle or a 4x4 taxi from Stepantsminda (about 45-60 minutes); an ordinary rental car will struggle on the final stretch. Weather turns fast above the treeline — carry a warm layer even on a clear morning.', 'Morning start, to be back below cloud before afternoon storms build', 300, '5 hr', NULL, NULL, 'Free', 'Juta', 42.578532, 44.744107, 'The first hour along the valley floor suits older, fit kids; the full route to the lake is a proper trek.', false, ARRAY['hike', 'scenic', 'cool']::TEXT[], 8, NULL, NULL),
  ('gudauri-kazbegi-paragliding', 'gudauri-kazbegi', 'Gudauri Tandem Paragliding', 'Launch from the ski slopes and float 15-20 minutes over the Gudauri valley with a licensed tandem pilot.', 'Several operators based around the Gudauri resort run tandem paragliding, launching from points on the upper slopes reached by chairlift and landing in a field near the main road. Flights themselves run roughly 15-20 minutes and need nothing more than closed shoes — the licensed pilot does the flying. It''s entirely weather-dependent: wind or low cloud delays or cancels flights outright, so treat it as a flexible add-on rather than something to schedule right before you need to leave.', 'Meeting points vary by operator — confirm the exact pickup spot when booking. Bring cash; card readers aren''t reliable roadside. Photo and video packages cost extra on top of the flight price.', 'Calm mid-morning conditions; afternoons often bring wind', 60, '1 hr', 100, 250, '₾100-250 per person (video/photo packages extra)', 'Gudauri', 42.477, 44.479, 'Most operators set a minimum age, commonly around 10-12 — confirm before booking with kids.', true, ARRAY['thrill', 'scenic']::TEXT[], 9, NULL, NULL),
  ('gudauri-kazbegi-horse-riding', 'gudauri-kazbegi', 'Kazbegi Horse Riding', 'Guided rides into the Sno valley meadows — beginner-friendly, with Kazbek and the Gergeti glacier in view.', 'Stables at the edge of Stepantsminda run guided horse treks into the Sno valley and along the Artkhmo gorge, typically 2.5-4 hours depending on the route, crossing open alpine pasture with the Gergeti glacier visible behind you. No riding experience is assumed — horses are led or closely guided at a walk or gentle trot. Longer routes push toward Truso valley territory for more confident riders.', 'Book the evening before through your guesthouse or directly at a stable — this is a first-come local operation, not a call-ahead agency. Wear long trousers and closed shoes; ask about helmets, as provision varies by stable.', 'Morning, before afternoon cloud and wind pick up', 180, '3 hr', 130, 250, '₾130-250 per person, depending on route and duration', 'Stepantsminda', 42.648, 44.638, 'Fine for confident kids; ask the stable about a minimum age or lead-rein option for younger riders.', true, ARRAY['kids', 'scenic']::TEXT[], 10, NULL, NULL),
  ('gudauri-kazbegi-rooms-restaurant', 'gudauri-kazbegi', 'Kazbegi Kitchen at Rooms Hotel', 'Georgian plates on a terrace framed by Kazbek and the Gergeti church — the region''s one genuine destination meal.', 'The restaurant at Rooms Hotel Kazbegi, a converted Soviet-era sanatorium turned design hotel, opens onto a floor-to-ceiling window wall and terrace facing Mount Kazbek and Gergeti Trinity Church across the valley — reason enough to book even before the food arrives. The kitchen runs a Georgian-leaning menu with a strong Georgian wine list, and pulls day-trippers as well as hotel guests, so it fills up at lunch and around sunset.', 'Recent reviews flag service as slow when the terrace is full — go for the view and pace yourself rather than expecting a quick meal. Reserve ahead in peak summer, especially for a terrace table at golden hour. Menu pricing below is approximate, built from limited review data rather than a published menu — confirm current prices on arrival.', 'Golden hour, for the light on Kazbek', 90, '1.5 hr', 40, 90, '₾40-90 per main course (approximate — confirm on menu)', 'Stepantsminda', 42.658943, 44.65079, 'Full-service restaurant rather than a kid-focused spot, but staff are used to families passing through.', true, ARRAY['scenic', 'evening']::TEXT[], 11, NULL, NULL),
  ('gudauri-kazbegi-museum', 'gudauri-kazbegi', 'Stepantsminda History Museum', 'A small indoor museum on regional history and writer Alexander Kazbegi — the region''s real bad-weather fallback.', 'Housed in what was once a memorial house for 19th-century Georgian writer Alexander Kazbegi (after whom the town was long named), this compact museum mixes his personal effects with archaeological and ethnographic pieces from the wider Khevi region — old weapons, textiles, and photographs of the valley before the road existed. It''s a modest collection rather than a headline sight, but it''s the one genuinely indoor option in a region where weather closes the mountains often, and it gives useful context for what you''ve been driving past.', 'Closed Mondays; open roughly 10:00-18:00 other days. Some recent visitor reports mention irregular hours or temporary closures, so it''s worth confirming locally before making it your rain-day plan.', NULL, 40, '40 min', 1, 3, '₾3 adults, ₾1 students', 'Stepantsminda', 42.66068, 44.64328, 'Small and quiet rather than interactive — better suited to older kids with some patience.', false, ARRAY['cool']::TEXT[], 12, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 12.
SELECT count(*) AS gudauri_kazbegi_places
  FROM catalog_places WHERE region_id = 'gudauri-kazbegi';
