-- Migration 10 — Georgia catalog places: Shida Kartli
--
-- GENERATED FILE. Source of truth is content/catalog/shida-kartli.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Gori & the Uplistsikhe rock town',
  summary       = 'Shida Kartli is Georgia''s hot, flat inland heartland — wheat fields and vineyards ringing Gori, the birthplace of Stalin, with Uplistsikhe''s rock-cut cliff city a short drive east and a scatter of quiet frescoed monasteries most visitors drive straight past. It works well as a long day trip from Tbilisi or a one-night stop on the way west to Kutaisi. The region''s northern edge touches the unmarked administrative boundary line (ABL) with Russian-occupied South Ossetia, roughly 20km beyond Gori — every place in this catalog sits well south of it, but it''s worth knowing it''s there and not to head north off the main highway toward Tskhinvali.',
  when_to_go    = 'Best in spring (April-May) and autumn (September-October) — this is a hot, dry inland basin, and Uplistsikhe, Gori Fortress, and Ateni Sioni all sit fully exposed with essentially no shade. In July-August, do the outdoor sites before 10am or after 5pm and carry more water than feels necessary; midday heat here is sharper than in Tbilisi or the mountains. Winter is cold but quiet, with a discounted Uplistsikhe ticket and near-empty monasteries, though Rkoni''s dirt access road gets rough after rain or snow.',
  getting_there = 'Gori is about 85km (1-1.5hr) from Tbilisi on the S1 highway, good tarmac the whole way and the main road toward Kutaisi and the west, so most itineraries pass through anyway. Uplistsikhe is a further 15-20 minutes east of Gori on paved roads. Frequent marshrutkas run from Tbilisi''s Didube station to Gori (roughly 1.5hr, a few GEL); getting on to Uplistsikhe, Ateni, Kintsvisi, or Rkoni by public transport is thin to nonexistent, so a car, taxi, or a day tour based out of Gori is the practical option for the outlying sites.',
  base_towns    = 'Gori is the obvious base — central for Uplistsikhe, the Ateni valley, and the Stalin-era sites, with a handful of budget hotels and guesthouses. Most visitors coming from Tbilisi treat the region as one long day trip or a single-night stopover on the drive toward Kutaisi rather than a multi-night stay.'
WHERE id = 'shida-kartli';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('shida-kartli-gori-fortress', 'shida-kartli', 'Gori Fortress', 'A free hilltop citadel above Gori with sweeping views over the town and the Mtkvari valley.', 'Gori''s fortress sits on the volcanic-looking hill directly above the town center, rebuilt repeatedly from an early-medieval core through the 17th-19th centuries as control of the town changed hands. Steps lead up from the streets below to a compact circuit of stone walls and towers — there''s no ticket booth, gate, or fixed exhibit, just open access to climb and look around. From the top you get a full panorama over Gori''s grid, the Mtkvari river, and the plain running out toward Uplistsikhe and the hills beyond. It''s a five-minute climb rather than a hike, which makes it an easy add-on before or after the Stalin Museum a few blocks away.', 'No ticket booth or fixed hours — it''s an open, unstaffed site accessible any time there''s daylight. Stone stairs and wall-top sections are uneven and often unguarded, so watch your footing and supervise kids closely. No shade anywhere at the top; go early or late in summer. The hills visible to the north are well short of the South Ossetia boundary line (roughly 20km further on) — nothing about the view itself is close to it.', 'Early morning or golden hour', 30, '30 min', NULL, NULL, 'Free', 'Gori', 41.9861, 44.10806, 'Kids enjoy scrambling along the walls, but there are unguarded drops in places — hold hands near the edges rather than letting them range freely.', false, ARRAY['scenic', 'walk', 'kids']::TEXT[], 1, NULL, NULL),
  ('shida-kartli-stalin-museum', 'shida-kartli', 'Stalin Museum, Gori', 'The still-operating state museum dedicated to Gori''s most famous native son.', 'Gori''s state museum occupies a grand building constructed specifically to house it, and a guided visit moves through exhibition halls of personal photographs, gifts sent by world leaders, and personal effects, then out to a modest childhood home preserved under a marble pavilion, and finally to Stalin''s armored green private railway carriage parked behind the building. The museum is still state-run and presents its subject largely through his own biography and personal artifacts rather than a critical, contextualized account of the purges and famine — visitors going in expecting the latter should know this isn''t primarily that kind of museum. What''s actually here is real and well preserved: the halls, the birth house, and the carriage.', 'Open daily except Monday, roughly 10:00-18:00 (10:00-17:00 in winter) — some sources note Monday closures can shift in the low season, so check locally if visiting outside summer. Full ticket with guide, birth house, and carriage runs about ₾15; skip the carriage for ₾10, or see the carriage alone for ₾5.', 'Morning, before tour groups arrive', 90, '1.5 hr', 5, 15, '₾5-15 (full complex incl. birth house & rail carriage with guide ₾15)', 'Gori', 41.987222, 44.113611, 'The armored green railway carriage is the highlight for most kids; the exhibition halls move at a slow, guided pace, so temper expectations for younger children.', false, ARRAY['cool', 'kids']::TEXT[], 2, NULL, NULL),
  ('shida-kartli-gori-museum', 'shida-kartli', 'Sergi Makalatia Gori Historical & Ethnographic Museum', 'A quiet indoor museum on Gori''s deeper history, including a sobering room on the 2008 war.', 'A low-traffic counterpart to the Stalin Museum a few streets away, this local history museum covers Gori and the wider Shida Kartli region through archaeological finds, traditional Georgian costumes and textiles, jewelry, and household furniture. A small dedicated room holds photographs and artifacts from the August 2008 Russia-Georgia war, when Gori itself was shelled and briefly occupied — a sober, factual counterpoint to the rest of the collection. It''s compact enough to see properly in under an hour and rarely has more than a handful of other visitors, which makes it a genuine change of pace from the crowds at the Stalin Museum.', 'Open 10:00-18:00 Tuesday through Saturday; closed both Sunday and Monday, which is unusual for the region — plan around it. Address is 12 Kirion II Street, a few blocks from the Stalin Museum; the exact building isn''t well mapped, so ask locally or at the tourist information office if you can''t find it.', NULL, 40, '40 min', 3, 3, '₾3 (adults; discounted for students and schoolchildren)', 'Gori', 41.9835, 44.1108, 'The 2008 war room includes photographs of shelling damage that may not suit the youngest visitors — worth a quick preview if traveling with small kids.', false, ARRAY['cool', 'walk']::TEXT[], 3, NULL, NULL),
  ('shida-kartli-chinebuli', 'shida-kartli', 'Chinebuli', 'The unpretentious local favorite across from the Stalin Museum, serving Gori''s best-value khinkali.', 'Chinebuli sits directly across the street from the Stalin Museum but pulls as many Gori locals as tourists, which says something about a menu built on solid, inexpensive Georgian standards rather than a captive-audience markup. Order khinkali by the piece, kharcho soup, or an Adjaruli or Mingrelian khachapuri, and expect generous portions for the price. It''s a straightforward, no-frills room rather than a scenic destination in itself, but it''s the kind of reliably good, honestly priced place regulars keep returning to rather than a tourist-trap refuel stop.', 'No reservations needed outside large groups; cash is the safer bet. Diners commonly report paying roughly ₾20-30 per person for a full meal — treat this as an estimate from reviewer reports rather than a fixed, published menu price.', 'Lunchtime', 60, '1 hr', 20, 30, '₾20-30 per person (based on diner reports, not a published menu)', 'Gori', 41.987739, 44.114142, 'Big, shareable Georgian classics and a casual, noisy room — no need to worry about restaurant manners here.', false, ARRAY['wine', 'kids']::TEXT[], 4, NULL, NULL),
  ('shida-kartli-uplistsikhe', 'shida-kartli', 'Uplistsikhe Cave Town', 'A cliffside city carved entirely from rock, inhabited from the Bronze Age to the Middle Ages.', 'Uplistsikhe is a city carved directly into a rocky hillside above the Mtkvari river, not a single structure — walking it means climbing through hundreds of rock-cut chambers, tunnels, wine cellars, grain pits, and a pagan altar hall, up to a 9th-10th century Christian basilica built into the rock at the summit. A marked path loops through the site, but it''s uneven, steep in places, and involves real scrambling over worn stone. The scale and age of the place — occupied from roughly the early Iron Age through the 13th-14th centuries — is the payoff; a small site museum near the entrance gives context before the climb. Give this considerably longer than it looks from the entrance; most visitors underestimate it.', 'Open daily except Monday, roughly 10:00-17:00 (later in peak summer) — confirm hours if visiting off-season. Entry is ₾15, sometimes discounted to around ₾7 in winter low season. There is no shade anywhere on the hillside — bring a hat, sunscreen, and more water than feels necessary, and wear real shoes; sandals are a bad idea on the worn rock.', 'Early morning, to beat both heat and tour buses', 120, '2 hr', 7, 15, '₾7-15 (winter off-season discount to ₾7)', 'Gori', 41.96553, 44.17119, 'Kids generally love clambering through the tunnels and pits, but the whole site is exposed rock with unguarded drops in places — keep a close hand on younger kids, especially in the heat.', false, ARRAY['cave', 'walk', 'scenic', 'kids']::TEXT[], 5, NULL, NULL),
  ('shida-kartli-ateni-sioni', 'shida-kartli', 'Ateni Sioni Church', 'A 7th-century domed church modeled on Jvari, with rare 11th-century frescoes still on its walls.', 'Modeled closely on Jvari Monastery near Mtskheta but built slightly later in the early 7th century, Ateni Sioni is a domed cross-in-square church standing alone above the Tana river in a quiet wine-growing valley about 10km south of Gori. Inside, the 11th-century frescoes are among the finest surviving medieval religious paintings in Georgia, depicting biblical scenes alongside portraits of Georgian nobility of the period. It sees a fraction of the visitors Jvari does despite the architectural similarity, and the valley setting — vineyard terraces climbing the slopes around it — is a big part of the appeal. It''s an active church, so expect it to be quiet rather than staffed.', 'No fixed visiting hours were found for this site — it''s generally accessible through the day, but if it''s locked, ask in the village for the caretaker. Free entry; donations welcomed. Modest dress (shoulders and knees covered) expected as at any working church.', 'Morning', 30, '30 min', NULL, NULL, 'Free', 'Ateni', 41.9039, 44.096, NULL, false, ARRAY['scenic', 'walk']::TEXT[], 6, NULL, NULL),
  ('shida-kartli-vacheishvili', 'shida-kartli', 'Vacheishvili Wine Cellar (Atenuri)', 'A family winery in the Ateni valley making Atenuri, once called "the wine of kings."', 'This small family winery in Ateni village makes Atenuri, a lightly sparkling white wine unique to this valley and made only from the local Chinuri and Goruli Mtsvane grapes — praised in old Georgian writing as fit for royalty. Walk the terraced vineyard and peek into the family cellar, a ten-minute stroll from Ateni Sioni church, and pick up a bottle to take home. It''s a genuinely small, family-run operation rather than a polished tourist winery, which is part of the appeal for anyone wanting a quieter alternative to the larger estates closer to Tbilisi.', 'Walking the grounds and cellar is free and informal, with no fixed tasting-room schedule. A sit-down tasting or meal needs to be arranged with the family in advance (via atenuri.ge) — the price for that experience isn''t published anywhere, so confirm it directly when you book. Bottled wine (e.g. Tavkveri or Chinuri) runs around ₾40 if you want to buy some to take home.', NULL, 45, '45 min', NULL, NULL, 'Free', 'Ateni', 41.913056, 44.093056, NULL, false, ARRAY['wine', 'scenic']::TEXT[], 7, NULL, NULL),
  ('shida-kartli-kintsvisi', 'shida-kartli', 'Kintsvisi Monastery', 'A forested 13th-century monastery hiding one of Georgia''s finest medieval fresco cycles.', 'Set on a wooded slope in the Dzama gorge about 25km from Gori, Kintsvisi is a monastic complex of three churches — the Church of the Virgin Mary, St. George, and St. Nicholas — plus a bell tower, shaded by surrounding trees rather than sitting exposed like most Shida Kartli sites. The Church of the Virgin Mary holds one of Georgia''s most celebrated fresco cycles, including a Hodegetria Virgin and a Communion of the Apostles scene rated among the finest surviving examples of medieval Georgian monumental painting. It''s a working, lightly visited monastery — expect to have the frescoes largely to yourself on a weekday.', 'The final stretch of road is unpaved but manageable in a normal car at a slow pace. Free entry, donations welcome; modest dress expected as at any active monastery. No food, water, or facilities on site.', 'Morning', 45, '45 min', NULL, NULL, 'Free', 'Kareli', 41.960533, 43.834309, NULL, false, ARRAY['scenic', 'walk', 'cool']::TEXT[], 8, NULL, NULL),
  ('shida-kartli-rkoni', 'shida-kartli', 'Rkoni Monastery & Queen Tamar Bridge', 'A ruined monastery reachable only by crossing a medieval queen''s bridge over the Tedzami River.', 'Rkoni is a ruined 7th-13th century monastery-and-fortress complex perched above the Tedzami river, reachable only by crossing a stone bridge locally attributed to Queen Tamar. From the bridge, a marked trail climbs the hillside past the monastery buildings to a small rock-hewn cave once used by resident monks, with views back down the narrow gorge. It''s one of the least-visited sites in this catalog — the access road past Garikula village is a rough dirt track that keeps the crowds away — and the surrounding valley is reportedly at its best in autumn foliage.', 'The last stretch from Garikula is an unpaved dirt road, slow going but passable in a normal car in dry weather; avoid it after heavy rain. No shops, water, or facilities anywhere near the site — bring everything you need. Phone signal is patchy for much of the approach, so download offline maps beforehand.', 'Autumn, for the foliage', 90, '1.5 hr', NULL, NULL, 'Free', 'Kaspi', 41.8075, 44.22472, 'The bridge crossing and cave scramble make this feel like a real adventure for kids, but there are no railings anywhere — hold hands on the bridge and near the cave opening.', false, ARRAY['hike', 'scenic']::TEXT[], 9, NULL, NULL),
  ('shida-kartli-surami', 'shida-kartli', 'Surami Fortress', 'A ruined hilltop fortress guarding the only road between eastern and western Georgia.', 'Surami''s ruined fortress sits on a hill above the small town, guarding the Surami (Rikoti) Pass — historically the only route connecting eastern and western Georgia, which is why whoever controlled this hill controlled the country''s main artery. What survives today is genuine ruins rather than a restored monument: a citadel, a palace footprint, and the small St. George church, rebuilt repeatedly between the 11th and 18th centuries. The fortress is the setting for "The Legend of Suram Fortress," a well-known Georgian folk tale and 1984 Sergei Parajanov film about a young man walled alive into the ramparts to keep them from collapsing. It''s a convenient stretch-your-legs stop on the long drive between Gori and Kutaisi or Borjomi, not a destination in its own right.', 'Free, unstaffed, and open access at any time — the ruins have uneven footing, so wear real shoes. Surami town, right below the fortress, is well known for roadside churchkhela stalls — a good stop to combine with the climb.', NULL, 30, '30 min', NULL, NULL, 'Free', 'Surami', 42.025, 43.5639, 'Climbing around the ruined walls is the main appeal for kids — supervise near crumbled edges since there''s no fencing.', false, ARRAY['scenic', 'walk', 'kids']::TEXT[], 10, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 10.
SELECT count(*) AS shida_kartli_places
  FROM catalog_places WHERE region_id = 'shida-kartli';
