-- Migration 10 — Georgia catalog places: Kakheti
--
-- GENERATED FILE. Source of truth is content/catalog/kakheti.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Wine country',
  summary       = 'Georgia''s wine heartland: rolling vineyards along the Alazani valley, hilltop monasteries visible for miles, and family-run cellars where wine has been made in buried clay qvevri for 8,000 years. It rewards a slower pace than the mountains — plan a loop between Sighnaghi and Telavi rather than a single day trip from Tbilisi.',
  when_to_go    = 'April–June and September–October are best: mild days, green or gold vineyards, and (in autumn) the rtveli grape harvest, when family wineries let visitors help pick and tread grapes — book ahead, it''s the busiest season. July–August push 30–35°C in the Alazani valley, so do cellar visits and monastery walks in the morning or early evening and nap through midday. Winter is quiet and monasteries stay open, but days are short and some small family cellars close informally between tourist groups.',
  getting_there = 'From Tbilisi it''s about 1.5–2 hours to Sighnaghi via the newer Kakheti Highway through Sagarejo (well paved, fast), or roughly 2–2.5 hours to Telavi over the scenic but winding Gombori Pass. Both routes are fine in a normal car; only the last stretch to David Gareja needs a high-clearance vehicle or organized tour. Marshrutky (shared minibuses) run from Tbilisi''s Isani/Samgori station to Telavi and Sighnaghi, but a rental car or driver gives far more flexibility for hopping between wineries.',
  base_towns    = 'Sighnaghi (romantic hilltop old town, best for the walls, Bodbe, and dinner at Pheasant''s Tears) or Telavi (bigger, more central, best base for day trips to Tsinandali, Alaverdi, Ikalto, Gremi and the Kvareli-area cellars).'
WHERE id = 'kakheti';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('kakheti-sighnaghi-walls', 'kakheti', 'Sighnaghi Old Town Walls', 'Walk the ramparts of Georgia''s ''City of Love'' above an endless view of the Alazani valley.', 'Sighnaghi''s 18th-century defensive walls loop around the hilltop old town, with cobbled lanes, balconied houses, and watchtowers you can climb for a free panorama over the vineyards below toward the Caucasus. It''s an easy, mostly flat stroll connecting cafés, wine shops, and the town''s famous 24-hour wedding registry. Come at golden hour when the light hits the valley and the day-trip buses have thinned out.', 'Free and open at all hours; some rampart sections have unguarded drops, so keep an eye on small kids. Central streets are cobbled and steep in patches — fine for a stroller on the main square but not everywhere.', 'Late afternoon, for the light over the valley', 60, '1 hr', NULL, NULL, 'Free', 'Sighnaghi', 41.6205, 45.9167, 'Kids enjoy spotting the watchtowers and running the flatter stretches; nothing here needs supervision beyond normal wall-edge caution.', false, ARRAY['scenic', 'walk']::TEXT[], 1, NULL, NULL),
  ('kakheti-bodbe-monastery', 'kakheti', 'Bodbe Monastery of St. Nino', 'A working nunnery holding Georgia''s most venerated grave, with a cypress walk down to a holy spring.', 'Bodbe Convent, just outside Sighnaghi, holds the tomb of St. Nino, the woman credited with converting Georgia to Christianity in the 4th century — it''s one of the country''s most important pilgrimage sites. The cathedral and grounds are free to visit, and a path lined with cypress trees leads steeply down through forest to St. Nino''s spring, a popular (very cold) dip for the devout. Give the walk down and back at least 30 minutes on top of the church visit.', 'Strict dress code: women need a headscarf and skirt/wrap covering the knees (free wraps at the gate if you forget), men need long trousers. No photos or video inside the churches, and entry pauses during services. The path down to the spring is steep, uneven, and has no rail — supervise kids closely.', 'Morning, before tour groups arrive', 60, '1 hr', NULL, NULL, 'Free', 'Sighnaghi', 41.5998, 45.9033, 'The dress-code fuss and the request for quiet inside the church can be a lot for younger kids; the walk to the spring is the part they''ll actually enjoy.', false, ARRAY['scenic', 'walk']::TEXT[], 2, NULL, NULL),
  ('kakheti-alazani-viewpoint', 'kakheti', 'Alazani Valley Viewpoint Picnic', 'Pull off the Sighnaghi road for open space, a huge valley view, and a picnic with zero wine involved.', 'The road between Sighnaghi and Bodbe drops off the hilltop with wide, unbroken views across the Alazani valley''s vineyards toward the Caucasus — a natural spot to stop, spread a blanket, and let kids run without a tasting room or a church dress code in sight. Pick up bread, cheese, churchkhela, and fruit at a Sighnaghi shop or market stall beforehand. There''s no infrastructure here, which is the point: open grass, big sky, and a view worth lingering over.', 'No facilities, shade, or marked parking — bring water and a shade umbrella for midday. Treat it as a pull-off, not a ticketed site; exact best spots shift with roadworks.', 'Sunset', 40, '40 min', NULL, NULL, 'Free', 'Sighnaghi', 41.607, 45.905, 'The one stop on this list built entirely around kids having room to run around — no tasting, no church silence, no queue.', false, ARRAY['scenic', 'kids', 'walk']::TEXT[], 3, NULL, NULL),
  ('kakheti-pheasants-tears', 'kakheti', 'Pheasant''s Tears', 'Sighnaghi''s destination dinner: qvevri natural wine and a long Georgian table in a converted old-town house.', 'Pheasant''s Tears is a pioneer of Georgia''s natural-wine revival, run out of a rustic dining room and courtyard in Sighnaghi''s old town, pairing its own qvevri-made wines with a full spread of Georgian dishes — khinkali, lobio, badrijani, fresh bread from the on-site tone oven. It runs as a proper sit-down dinner rather than a quick tasting stop, with live music some evenings. Make it the anchor of an evening in Sighnaghi rather than a mid-day stop between sights.', 'Open daily 12:00–23:00 with the kitchen closing around 22:00. It''s popular with tour groups in summer — reserve ahead or arrive right at opening if you want to avoid a wait. Around ₾40-80 a head for dinner, and wine is charged on top.', 'Dinner', 90, '1.5 hr', 40, 80, '₾40-80', 'Sighnaghi', 41.6212, 45.9153, 'Kid-friendly menu overlap (bread, khinkali, cheese) but it''s a slow, multi-course dinner — better for kids used to sitting through a long meal than for very young ones past bedtime.', false, ARRAY['wine', 'evening']::TEXT[], 4, NULL, NULL),
  ('kakheti-tsinandali-estate', 'kakheti', 'Tsinandali Estate', 'The Chavchavadze family''s 19th-century manor and gardens, with a museum, old winery, and resort complex.', 'Tsinandali was the country estate of poet-nobleman Alexander Chavchavadze, whose 19th-century manor house, English-style dendrological park, and original stone winery now form a museum complex near Telavi. A guided visit takes you through period rooms and the old cellar (with a tasting option), followed by self-guided time in the gardens among cedars, magnolias, and peacocks. It''s the most polished, least rustic of the region''s wine stops — good for a first, easy introduction before the smaller family cellars.', 'Tickets: 5 ₾ (students), 10 ₾ (standard museum + old winery visit), 12 ₾ with a glass of wine included; under-6s free. There''s an on-site café/restaurant and a modern hotel complex next door.', 'Morning, before the day gets hot', 90, '1.5 hr', 5, 12, '₾5-12', 'Telavi', 41.8839, 45.4728, 'The gardens (and peacocks) are the real kid draw; the museum rooms and tasting room are a walk-through rather than hands-on, so budget more garden time than museum time for younger kids.', false, ARRAY['wine', 'scenic', 'kids']::TEXT[], 5, NULL, NULL),
  ('kakheti-alaverdi-cathedral', 'kakheti', 'Alaverdi Cathedral & Monastery', 'A working monastery under Georgia''s tallest historic cathedral, with monks still making wine in a 1,000-year-old cellar.', 'Alaverdi''s 11th-century cathedral rises over 50 meters — it was the tallest building in Georgia for nearly a thousand years — and stands alone in a walled compound surrounded by the monastery''s own vineyards. The monks continue a winemaking tradition that runs through a cellar dated to the 10th–12th centuries, and the grounds are quiet compared to the more touristed stops nearby. It''s as much a working religious community as a sight, so visits are respectful rather than rushed.', 'Free to enter; dress modestly (covered shoulders/knees) as at any active Georgian monastery. The cathedral can close to visitors during services, and whether the monastery''s own wine is available to taste or buy on a given day varies — ask on arrival rather than counting on it.', 'Morning', 45, '45 min', NULL, NULL, 'Free', 'Akhmeta', 42.0325, 45.377222, 'Mostly a look-and-walk stop for kids — the scale of the cathedral (Georgia''s tallest for centuries) is the thing worth pointing out to them.', false, ARRAY['scenic']::TEXT[], 6, NULL, NULL),
  ('kakheti-ikalto-academy', 'kakheti', 'Ikalto Monastery & Academy', 'Quiet ruins of Georgia''s first academy — where the poet Rustaveli reputedly studied — with almost nobody else there.', 'Ikalto is the stop most visitors skip in favor of Alaverdi, which is exactly its appeal: a 6th-century monastery complex with the roofless stone ruins of a 12th-century academy that once taught theology, philosophy, and winemaking alongside the sciences. A huge sunken winepress and rows of ancient qvevri sit among the ruins, a reminder that wine education was part of the curriculum. It''s a short, unstructured wander rather than a formal tour — good for a break between bigger stops without the crowds.', 'Free, no ticket booth or facilities on site. Ground is uneven stone rubble in places — watch footing, and bring water since there''s no shade to speak of.', NULL, 40, '40 min', NULL, NULL, 'Free', 'Telavi', 41.936944, 45.381111, 'Ruins kids can actually clamber around near (with supervision) rather than a hushed interior — a good antidote after the more formal Bodbe/Alaverdi stops.', false, ARRAY['scenic', 'walk']::TEXT[], 7, NULL, NULL),
  ('kakheti-twins-cellar', 'kakheti', 'Twins Wine Cellar', 'A small family qvevri cellar in Napareuli village — real working marani, not a tour-bus stop.', 'Twins Wine Cellar is run by twin brothers continuing their family''s Kakhetian-method winemaking in a cellar holding well over 100 buried qvevri, most sized to hold several tonnes of wine each. The hour-long visit walks through the vineyard, the working cellar, the tasting room, and even the small lab, ending with six to ten wines poured by the family themselves rather than a hired guide. It''s the most personal, least polished of the region''s wine stops — book ahead, as it runs on reserved slots rather than walk-in traffic.', 'Advance booking required, with a deposit taken ahead of the visit; open daily 11:00–19:00. Small groups only (roughly 3–15 people per session). Rural cellars like this typically prefer cash.', NULL, 60, '1 hr', 17, 17, '₾17', 'Napareuli / Telavi', 41.9111, 45.6072, 'Honest version: kids don''t taste and there isn''t a dedicated kids'' activity here, so it works best for kids old enough (roughly 8+) to sit through an hour of adult conversation and pouring — bring something to occupy younger ones.', true, ARRAY['wine']::TEXT[], 8, NULL, NULL),
  ('kakheti-khareba-tunnel', 'kakheti', 'Khareba Wine Tunnel', 'Taste inside 7.7 km of cool underground tunnels carved for Soviet-era wine storage near Kvareli.', 'Khareba ages and stores its wine in a network of hillside tunnels originally built for military use, now a constant, cellar-cool underground gallery you walk through on the way to the tasting room. Tours run from a basic tunnel walk-through with a short tasting up to fuller packages that add the viewing tower and a terrace restaurant with valley views. Because it''s underground, it''s naturally one of the best hot-day or bad-weather options in the region — the temperature barely moves whatever''s happening outside.', 'Open daily. Prices scale with the package — a simple tunnel-and-tasting visit runs well under the fuller food-and-workshop packages (see the separate family workshop listing). Book ahead in high season to avoid arriving alongside a big tour-bus group.', 'Morning, before tour-bus groups arrive', 90, '1.5 hr', 15, 30, '₾15-30', 'Kvareli', 41.933, 45.822, 'The tunnel itself is the kid highlight (cool, cave-like, a bit spooky in a fun way); ask for grape juice instead of wine at the tasting table rather than expecting them to sit it out.', false, ARRAY['wine', 'cool', 'kids']::TEXT[], 9, NULL, NULL),
  ('kakheti-khareba-kids', 'kakheti', 'Khareba Family Workshops', 'While the adults taste in the tunnel, kids bake bread, dip churchkhela, and (in harvest season) tread grapes barefoot.', 'Alongside its wine tunnel, Khareba''s touristic complex runs hands-on stations aimed squarely at families: baking Georgian bread in a tone oven, dipping churchkhela (the walnut-and-grape-must candle-shaped candy), and watching or joining a chacha distillation demo. During the September–October rtveli harvest, the highlight is treading grapes barefoot in a satsnakheli, the traditional wooden press, alongside seasonal grape picking. It''s the honest answer to ''what do the kids do'' during the adults'' tasting next door.', 'Arrange this alongside your tunnel/tasting booking rather than expecting to walk in and join — the fuller package (workshops plus a cooked meal) runs well above a bare tunnel visit. Grape treading is seasonal (roughly September–October); confirm what''s actually running when you book outside harvest time.', NULL, 60, '1 hr', 30, 55, '₾30-55', 'Kvareli', 41.9325, 45.8228, 'This is the purely-for-kids stop on the list — no tasting room, no dress code, no sitting still.', true, ARRAY['kids', 'cool']::TEXT[], 10, NULL, NULL),
  ('kakheti-gremi', 'kakheti', 'Gremi Royal Church & Tower', 'Climb the bell tower of a 16th-century royal capital for a wraparound view of the Alazani valley.', 'Gremi was the capital of the Kingdom of Kakheti until a Persian invasion destroyed it in 1615; what survives is the domed Church of the Archangels, a three-story royal tower you can climb, defensive walls, and a small museum of medieval artifacts inside the tower itself. The climb up narrow stone stairs to the bell level is the main event for most kids, rewarded with an open view over the vineyards and hills. It''s a compact, quick stop that pairs naturally with a Kvareli-area wine day.', 'Entry 10 ₾; open roughly 10:00–17:00, though hours can shift off-season — worth confirming same-day if visiting late afternoon. The tower stairs are steep and narrow.', NULL, 60, '1 hr', 10, 10, '₾10', 'Kvareli', 42.001944, 45.66, 'The tower climb is the draw — steep, narrow stairs that most kids find genuinely exciting rather than a chore.', false, ARRAY['scenic', 'walk', 'kids']::TEXT[], 11, NULL, NULL),
  ('kakheti-david-gareja', 'kakheti', 'David Gareja Monastery Complex', 'A remote cave-monastery cut into a semi-desert ridge, with a hike to frescoes right on the Azerbaijan border.', 'David Gareja is a sprawling complex of monasteries carved into a dry, canyon-like ridge on Georgia''s semi-desert eastern edge, founded in the 6th century and still home to a small community of monks. The main Lavra monastery is a fairly easy walk from the parking area, but the famous frescoes at the Udabno complex require a steeper, exposed uphill hike along the ridge — with genuinely no shade. It''s the most remote and least polished stop on this list, worth the detour for the landscape alone but best treated as a half-day commitment once driving time is added.', 'Free entry (donations welcome); the final approach road is rough and best done in a high-clearance vehicle or with an organized tour, especially after rain. Go early to avoid the brutal midday heat on the exposed hike. The Udabno fresco complex sits directly on the disputed Georgia–Azerbaijan border and access there has been periodically restricted — check current status with a local guide or tour operator before counting on seeing it.', 'Spring or autumn morning', 150, '2.5 hr', NULL, NULL, 'Free', 'Sagarejo', 41.454444, 45.356667, 'The Lavra monastery itself is manageable for most kids; the steep, shadeless climb to the Udabno frescoes is a real hike better suited to kids roughly 8+ who can handle heat and exposure.', false, ARRAY['cave', 'hike', 'scenic']::TEXT[], 12, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 12.
SELECT count(*) AS kakheti_places
  FROM catalog_places WHERE region_id = 'kakheti';
