-- Migration 10 — Georgia catalog places: Tbilisi
--
-- GENERATED FILE. Source of truth is content/catalog/tbilisi.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'City, views, sulfur baths',
  summary       = 'Georgia''s capital sprawls along a bend in the Mtkvari River, stacking Persian-tiled bathhouses, Soviet-era cable cars, and a UNESCO-adjacent old town under a hilltop fortress. It''s a genuinely walkable city for a family: the sights cluster into a few compact neighborhoods, most of the outdoor ones are free, and cable cars turn steep hillsides into a ride rather than a climb. Expect hot, dry middays in summer and beautiful, cooling evenings, with the sulfur baths and the national museum as your indoor refuge when the heat — or a rainy day — demands it.',
  when_to_go    = 'Best April-June and September-October for mild days. July-August is hot and dry at midday (often 32-35°C) but evenings cool off nicely, so front-load sightseeing to before 11am and after 5pm and save midday for the museum, a bathhouse, or a pool. Winter (Dec-Feb) is cold but every sight here stays open and crowds thin right out.',
  getting_there = 'Tbilisi International Airport (TBS) sits about 18 km southeast of downtown. Bolt or Yandex Go from the arrivals hall run roughly ₾20-30 and take 30-40 minutes depending on traffic — agree the fare or confirm the in-app price before getting in, since unmetered taxi touts at the airport routinely try to overcharge arriving tourists. Bus 337 runs from outside arrivals into the center roughly every 20-30 minutes (about 06:50-23:00) for ₾1 with a MetroMoney card, taking about 50 minutes — cheap but slow with luggage and kids. The airport-to-station rail link has not run since 2023, so don''t plan around it. Once in the city, buy a MetroMoney card (₾2 non-refundable deposit) at any metro station or kiosk: it covers the metro, city buses, and both cable cars, with the first ride costing ₾1 and any transfer within 90 minutes free. The metro is fast for crossing town but has only two lines and few elevators, so a folding stroller travels better than a pram. Bolt and Yandex Go are cheap and reliable for door-to-door hops (often under ₾1/km), especially in the heat or after dark, while the old town and Rustaveli Avenue are best covered on foot.',
  base_towns    = 'Base in or around the Old Town (Sololaki, Abanotubani) for walkability to the sights, or in Vera/Vake for a quieter, more residential feel with good restaurants and closer access to Turtle Lake and the Botanical Garden. Neither choice locks you out of anything here — nothing described below is more than a 15-20 minute Bolt ride from the other.'
WHERE id = 'tbilisi';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('tbilisi-old-town', 'tbilisi', 'Old Town Wander (Sioni & Abanotubani)', 'Cobbled lanes and carved wooden balconies that thread from Sioni Cathedral down into the bathhouse district.', 'Start at Sioni Cathedral and wander the pedestrianized lanes of Old Tbilisi, past ornate carved wooden balconies, small courtyards, and cafes selling churchkhela and Georgian wine. The streets funnel naturally down into Abanotubani, the brick-domed sulfur bath district, and up toward the Narikala cable car, so this isn''t a detour — it''s the connective tissue between the neighborhood''s other stops. Photogenic corners appear constantly and there''s no real route to get wrong. Evenings are best: the heat breaks, lanes fill with locals, and restaurant terraces open up.', 'Free to wander; the cobbles and occasional steps aren''t stroller-friendly in every lane, so a carrier works better for the youngest kids.', 'Early evening, once the midday heat breaks', 90, '1.5 hr', NULL, NULL, 'Free', 'Tbilisi', 41.691314, 44.807525, 'Flat-ish and easy to bail out of early if legs give out — there''s an ice cream or churchkhela stall every block.', false, ARRAY['walk', 'evening']::TEXT[], 1, NULL, NULL),
  ('tbilisi-narikala', 'tbilisi', 'Narikala Fortress & Cable Car', 'A 90-second cable car ride over the old town to a hilltop fortress with the best views in the city.', 'The cable car climbs from Rike Park to Narikala ridge in under two minutes, giving instant panoramic views over the old town''s tiled roofs, the Mtkvari River, and the giant Mother of Georgia statue standing guard above. From the upper station, walk the fortress walls and ramparts along the ridge — parts of the fortress interior have been under intermittent restoration in recent years, so treat the walk and viewpoints as the main event rather than any single building. It''s the single best orientation point for the city and works at any time of day, though sunset is the local favorite. Most visitors ride up and then walk back down through the old town rather than paying for the cable car twice.', 'Cable car is ₾2.5 one-way / ₾5 return, paid with a MetroMoney card; runs roughly 10am-midnight in summer, shorter hours in winter. Check locally on the day for which fortress sections are open, since restoration works have opened and closed different areas over the past couple of years. No shade on the ramparts, so bring hats and water in summer.', 'Late afternoon into sunset', 75, '1 hr 15 min', 3, 5, '₾2.5-5', 'Tbilisi', 41.68778, 44.80861, 'The cable car ride itself is the highlight for most kids; the ramparts have some unguarded drops, so keep a hand on younger ones.', false, ARRAY['scenic', 'kids']::TEXT[], 2, NULL, NULL),
  ('tbilisi-sulfur-baths', 'tbilisi', 'Abanotubani Sulfur Baths', 'Soak in naturally hot sulfur water inside brick-domed bathhouses that give the district its name.', 'Abanotubani''s brick domes sit over natural hot sulfur springs that have drawn bathers since the city''s founding legend. Book a private room at Chreli-Abano, Bath House No. 5, or one of the smaller family-run baths for an hour soaking in the hot mineral pool, usually with a cold plunge pool and sauna included in the better rooms. Add the traditional kisa scrub — a brisk, full-body exfoliation with a rough mitt — as a separate paid extra if the whole family is up for it; it''s intense rather than relaxing, and not for the ticklish. The smell is genuinely sulfurous and the water can stain light swimwear, so bring a dark suit and don''t expect subtlety.', 'Private rooms run roughly ₾15-200/hour depending on the bathhouse and room grade; smaller side-street baths are the cheapest but most basic. The kisa scrub is a separate ₾10-30 charge plus a small tip for the attendant. Most small bathhouses are cash-only; Chreli-Abano is one of the few with online booking. Not recommended during pregnancy or with open skin conditions.', NULL, 75, '1 hr 15 min', 15, 200, '₾15-200', 'Tbilisi', 41.687454, 44.810772, 'Fine for kids as a novelty soak, but the scrub is intense and the sulfur smell is strong — let younger kids opt out rather than push it.', false, ARRAY['cool']::TEXT[], 3, NULL, NULL),
  ('tbilisi-bridge-rike', 'tbilisi', 'Bridge of Peace & Rike Park', 'A glass-and-steel footbridge that lights up after dark, linking the old town to a riverside park.', 'Michele De Lucchi''s curved glass canopy crosses the Mtkvari River in a wave of steel ribs that light up with a slow-changing LED pattern after sunset, genuinely striking rather than a gimmick. It connects the old town directly to Rike Park on the far bank, a modern riverside green space with open lawns, a playground, and the lower cable car station up to Narikala. The whole loop — bridge, park, a lap along the riverbank — makes an easy, flat, free evening outing that tires kids out without taxing anyone''s patience.', 'Free and always open; best after dark for the bridge lighting. The deck can get crowded and slick underfoot after rain.', 'After sunset', 45, '45 min', NULL, NULL, 'Free', 'Tbilisi', 41.6929, 44.8082, 'Flat and stroller-friendly, with a playground in Rike Park to burn off pre-dinner energy.', false, ARRAY['evening', 'scenic', 'walk']::TEXT[], 4, NULL, NULL),
  ('tbilisi-mtatsminda', 'tbilisi', 'Mtatsminda Park & Funicular', 'A century-old funicular hauls you up Tbilisi''s tallest hill to an amusement park with the whole city laid out below.', 'The 1905 funicular climbs from Chonkadze Street to the top of Mtatsminda mountain in about five minutes, one of the steepest rides of its kind still running. At the top, Mtatsminda Park has a Ferris wheel, a rollercoaster, and a handful of smaller rides alongside cafes and the best sunset view over the city — the ponchiki (fried dough) stall near the top station is a local ritual, not just a tourist trap. Entry to the park itself is free; you pay per ride or per funicular trip on a rechargeable card. Give it a full evening rather than a quick stop — the lit-up city after dark is the actual payoff.', 'Funicular is roughly ₾10 per ride (up and down charged separately) plus a ₾2 reusable card fee; rides inside the park are priced individually on the same card. Go up an hour or so before sunset to get a table or bench with a view before the evening rush.', 'Sunset into early evening', 150, '2.5 hr', 10, 40, '₾10-40', 'Tbilisi', 41.6933, 44.7802, 'One of the best kid stops in the city — funicular plus fairground rides plus donuts; pace it so the youngest doesn''t melt down before sunset.', false, ARRAY['kids', 'evening', 'scenic']::TEXT[], 5, NULL, NULL),
  ('tbilisi-sameba', 'tbilisi', 'Holy Trinity Cathedral (Sameba)', 'A colossal gold-domed cathedral on its own hilltop, the third-tallest Orthodox cathedral in the world.', 'Consecrated in 2004, Sameba dominates the Tbilisi skyline from Elia Hill on the river''s east bank, its gold cross topping out at over 100 meters. The scale is the point — vast interior spaces, a sweeping terraced approach, and views back over the old town from its own grounds. It''s an active cathedral rather than a museum piece, so expect services, incense, and a genuinely devotional atmosphere alongside the tourists. The grounds around it are open and easy to wander even if you skip the interior.', 'Free entry; modest dress required — shoulders and knees covered, headscarves for women, wraps usually available at the door. It sits up a hill with limited shade, so it pairs well with a short Bolt ride rather than a walk in summer heat.', 'Morning, before the heat builds', 40, '40 min', NULL, NULL, 'Free', 'Tbilisi', 41.6975, 44.81667, 'The sheer size registers with kids even when the theology doesn''t — good for a quick, low-effort stop.', false, ARRAY['scenic']::TEXT[], 6, NULL, NULL),
  ('tbilisi-chronicles', 'tbilisi', 'Chronicles of Georgia', 'Sixteen soaring bronze pillars on a hilltop above the Tbilisi Sea, dramatic and largely missed by day-trippers.', 'Unofficially called the ''Georgian Stonehenge,'' this unfinished monument stacks 30-35 meter bronze pillars carved with scenes from Georgian history and Biblical stories, arranged on Keeni Hill overlooking the Tbilisi Sea reservoir. Construction stalled decades ago and the site is still rough around the edges — no ticket booth, no gift shop, just the scale of the columns and a genuinely wide view over the water. It sits far enough from the old town that few tour groups bother, which is exactly the appeal for families who''ve had enough queues elsewhere.', 'Free; no formal opening hours or staff on site, so it''s accessible dawn to dusk. There''s a set of steps up from the car park and no railings around some of the columns, so keep an eye on kids who like to climb. Best reached by taxi or Bolt (about 20-25 min from the old town) — there''s no useful public transit link.', 'Late afternoon, for the light on the pillars', 40, '40 min', NULL, NULL, 'Free', 'Tbilisi', 41.770503, 44.810438, 'The giant carved pillars and open hilltop are a hit, but there are no railings in places — hold hands near the edges.', false, ARRAY['scenic']::TEXT[], 7, NULL, NULL),
  ('tbilisi-museum', 'tbilisi', 'Georgian National Museum (Treasury)', 'Millennia-old gold jewelry in a cool, air-conditioned hall, the city''s best answer to a scorching or rainy day.', 'The Simon Janashia building on Rustaveli Avenue houses the Museum of Georgia''s headline exhibits, above all the Archaeological Treasury: pre-Christian gold and silver work, including the famous small golden lion, pulled from burial sites across the country. A separate Soviet Occupation exhibit covers 20th-century history in more sobering detail, better suited to older kids and adults. The building is fully air-conditioned, making it the single best indoor refuge in the city on a 35°C afternoon or a rain-soaked morning.', 'Closed Mondays. Tickets run roughly ₾20-35 for adults, discounted for children and students; the Treasury sometimes needs a separate small fee or timed-entry slot in peak season — check at the desk.', 'Midday, as a heat or rain refuge', 90, '1.5 hr', 20, 35, '₾20-35', 'Tbilisi', 41.696043, 44.800221, 'The gold Treasury room holds younger kids'' attention better than the general history halls do — lead with that.', false, ARRAY['cool']::TEXT[], 8, NULL, NULL),
  ('tbilisi-dry-bridge', 'tbilisi', 'Dry Bridge Market', 'A sprawling flea market of Soviet medals, old cameras, carpets, and junk, spread along the riverside embankment.', 'Vendors lay out blankets and folding tables along Dry Bridge (Sukhi Khidi) most days, selling everything from Soviet military medals and porcelain to vinyl records, carpets, and genuine antiques mixed in with reproductions. It''s as much a browse-and-people-watch stop as a shopping trip — haggling is expected and part of the fun, even if you don''t buy anything. Late afternoon into evening is liveliest, when it''s cooler and more vendors are out.', 'Cash only, and haggle — first prices are inflated for tourists. Authenticity varies wildly on ''antique'' items; treat anything without solid provenance as a curiosity, not an investment. Busiest and best-stocked on weekends.', 'Late afternoon', 45, '45 min', NULL, NULL, 'Free', 'Tbilisi', 41.70124, 44.803312, 'More interesting for older kids who can browse independently than for younger ones — it''s a lot of standing and looking, not touching.', false, ARRAY['evening', 'walk']::TEXT[], 9, NULL, NULL),
  ('tbilisi-botanical-garden', 'tbilisi', 'Tbilisi Botanical Garden & Waterfall', 'A shaded gorge garden behind Narikala fortress, with a 22-meter waterfall as the payoff at the end of the path.', 'Tucked into the Tsavkisi-Tskali gorge just behind the Narikala ridge, this 128-hectare garden is a genuinely cool, green escape from the old town''s stone and heat — winding paths through thousands of plant species lead back to a 22-meter waterfall cutting straight down the rock face. It''s shaded for most of the walk, gently sloped rather than steep, and quiet even in high season since most visitors skip it for the fortress next door. The waterfall''s flow varies by season, fullest in spring and thinner by late summer, but it rarely runs dry.', '₾4 adult entry, ₾6 for a family ticket; open 9am-7:30pm year-round. The path to the waterfall is unpaved in places, so trainers work better than sandals. Bring water — there are few kiosks inside.', 'Late morning, before the midday heat', 90, '1.5 hr', 4, 6, '₾4-6', 'Tbilisi', 41.68611, 44.8075, 'Shaded, easy walking, and a real waterfall at the end — one of the better cool-off, low-effort stops for younger kids.', false, ARRAY['cool', 'walk', 'kids']::TEXT[], 10, NULL, NULL),
  ('tbilisi-turtle-lake', 'tbilisi', 'Turtle Lake (Kus Tba)', 'A short cable car over Vake Park to a hillside lake with pedal boats, cafes, and a 1km path around the water.', 'A short cable car ride from Vake Park lifts you to Turtle Lake, a modest reservoir on the northern slope of the Mtatsminda ridge that doubles as Tbilisi''s easiest lakeside outing. Rent a pedal boat, walk the roughly 1km path around the shore, or just sit at one of the lakeside cafes — it''s unhurried and genuinely local rather than built for tourists. The Open-Air Museum of Ethnography, with relocated wooden houses from across Georgia, sits on the hill just above if there''s appetite for one more stop.', 'Cable car from Vake Park is around ₾1-2 one-way on a MetroMoney card; a taxi up is also cheap and quick if you''d rather skip the ride. Lakeside cafes are pricier than average — budget for it or bring your own snacks. Water rides and full cafe service scale back in winter.', 'Late afternoon', 90, '1.5 hr', 1, 2, '₾1-2 (cable car)', 'Tbilisi', 41.700391, 44.754455, 'Pedal boats and open grass to run on make this one of the more relaxed, low-stakes afternoons for younger kids.', false, ARRAY['kids', 'water', 'walk']::TEXT[], 11, NULL, NULL),
  ('tbilisi-keto-kote', 'tbilisi', 'Keto da Kote', 'A Vera townhouse restaurant doing Georgian classics well enough to be a destination meal, not just a refuel.', 'Set in a restored townhouse in the Vera neighborhood, Keto da Kote serves the Georgian staples — khinkali, khachapuri, badrijani (walnut-stuffed eggplant rolls), mtsvadi — cooked with more care and better ingredients than the average tourist-strip version, and it''s earned a spot on regional ''best of'' lists for it. The terrace seating is the draw in warm weather; the menu is long enough that a big table can order family-style and cover most of the greatest hits in one sitting. It''s a proper sit-down meal rather than a quick bite, so plan it as an evening anchor rather than a stop between sights.', 'Reserve 3-7 days ahead for a weekend table, especially for the terrace. Budget roughly ₾45-80 per person with wine. Busiest after 8pm.', 'Dinner, after 7pm', 90, '1.5 hr', 45, 80, '₾45-80', 'Tbilisi', 41.704825, 44.78857, 'Family-style ordering and familiar dishes (bread, dumplings, grilled meat) make this an easy sell for kids despite the more elevated setting.', true, ARRAY['wine', 'evening']::TEXT[], 12, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 12.
SELECT count(*) AS tbilisi_places
  FROM catalog_places WHERE region_id = 'tbilisi';
