-- Migration 10 — Georgia catalog places: Borjomi & Bakuriani
--
-- GENERATED FILE. Source of truth is content/catalog/borjomi-bakuriani.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Mineral springs, forest, cool air',
  summary       = 'Borjomi and Bakuriani are Georgia''s classic mountain escape from the summer heat: a spa town built around a famous sulfurous mineral spring, and a pine-forested ski resort 30km and 900m higher up the valley. Between them you get a mineral-water park with rides, forest trails and a hidden monastery, open-air sulfur pools, and — in winter — Georgia''s most beginner-friendly ski slopes. It''s cheap, green, noticeably cooler than Tbilisi, and genuinely built for families.',
  when_to_go    = 'This is the region Tbilisi families flee to when the capital hits 35C+ in July-August — Borjomi (820m) and especially Bakuriani (1,700m) run several degrees cooler, with real shade in the forests. In Borjomi Park, go before 9am (free entry, and not yet hot) and save the cable car and any hiking for late afternoon. December to late March is the other high season, when Bakuriani becomes Georgia''s main family ski resort (season roughly Dec 20 - Mar 29, confirm each year). Shoulder months (Apr-May, Oct-Nov) are quiet but grey and muddy, with limited lift and outdoor operation.',
  getting_there = 'Borjomi is about 150km / 2-2.5hr from Tbilisi via good tarmac (through Khashuri); marshrutkas run from Didube station (~3hr, a few GEL). Bakuriani is a further 30km / roughly 1hr by marshrutka or taxi from Borjomi (frequent minibuses, ~3-5 GEL), or reachable direct from Tbilisi by marshrutka/taxi (~3hr). The historic ''Kukushka'' narrow-gauge railway between Borjomi and Bakuriani has been suspended since 2020-2022 with no confirmed restart date — do not plan around it; treat any relaunch as a bonus, not a given.',
  base_towns    = 'Borjomi has the wider choice of hotels and spa guesthouses and sits closer to the park, sulfur pools and national park gate. Bakuriani, higher and cooler, is the better base in winter for ski-in convenience and in peak summer if you want maximum relief from the heat; it has plenty of family-oriented A-frame guesthouses but a thinner restaurant scene than Borjomi.'
WHERE id = 'borjomi-bakuriani';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('borjomi-bakuriani-central-park', 'borjomi-bakuriani', 'Borjomi Central Park', 'Georgia''s famous mineral-water park — spring tastings, a small funfair, and shaded paths along the Borjomula River.', 'The park is built around Ekaterine''s Spring, where you can fill a bottle straight from the source of Borjomi''s famous mineral water — warm, salty and sulfurous, and usually good for a laugh from kids on first taste. Beyond the spring pavilion there are shaded walking paths, cafes, a small funfair with rides for younger kids, and the old bottling-factory building (now a chess club and library) near the entrance. It''s the natural anchor for a Borjomi day and the starting point for both the cable car and the walk to the sulfur pools.', 'Entry is 5 GEL (free for kids under 8, and free for everyone 6-9am). Open 6am-8pm daily. Funfair rides are paid separately, on top of entry.', 'Before 9am (free entry, cooler) or early evening', 120, '2 hr', 5, 5, '₾5', 'Borjomi', 41.832216, 43.393669, 'Playground, small carnival rides, and a spring most kids find hilarious rather than pleasant — a good icebreaker for the trip.', false, ARRAY['kids', 'cool', 'walk']::TEXT[], 1, NULL, NULL),
  ('borjomi-bakuriani-ropeway', 'borjomi-bakuriani', 'Borjomi Park Cable Car', 'A cable car running since 1962 lifts you from the park to a forested plateau with a Ferris wheel and valley views.', 'This small cable car (up to 25 passengers per cabin) climbs from inside Central Park to a plateau above the gorge, with views over Borjomi town, the valley, and the Borjomula River. At the top there''s an old Ferris wheel, a small church, and a cafe serving Georgian food and drinks. The ride itself is only a few minutes, but it''s the easiest way in the region to get a proper elevated view without any walking.', 'Around 15 GEL one-way (roughly double for return); runs about 10am-8pm but can pause in high wind or heavy rain. Georgian ropeways have had past safety-driven closures nationwide, so confirm it''s running before you queue.', 'Late afternoon, for the light over the valley', 45, '45 min', 15, 25, '₾15-25', 'Borjomi', 41.8348, 43.3972, 'A short, exciting ride kids love; the old Ferris wheel at the top is a nice bonus if it happens to be running.', false, ARRAY['scenic', 'cool', 'kids']::TEXT[], 2, NULL, NULL),
  ('borjomi-bakuriani-sulfur-pools', 'borjomi-bakuriani', 'Borjomi Sulfur Pools', 'Open-air sulfur pools tucked in the forest above town — Borjomi''s quieter answer to Tbilisi''s bathhouses.', 'About a 3km walk (or short drive) through forest from Central Park, these open-air pools are fed by the same mineral springs that made Borjomi famous, but without Tbilisi''s crowds or architecture. Several pools run at different temperatures, and the setting — surrounded by trees, away from the town center — makes it feel more like a forest spring than a spa. It''s a good one to slot in on a cooler or overcast day, since the water stays warm regardless of the weather.', '15 GEL per person, free under 8; open 6am-8pm daily. Bring a towel and sandals. Can get crowded and less pleasant at peak summer midday — go early or on a cooler day.', 'Early morning, or a cool/overcast day', 60, '1 hr', 15, 15, '₾15', 'Borjomi', 41.845, 43.4, 'The sulfur smell can put younger kids off at first, but most come around once they''re in the warm water.', false, ARRAY['water', 'cool']::TEXT[], 3, NULL, NULL),
  ('borjomi-bakuriani-kharagauli-np', 'borjomi-bakuriani', 'Borjomi-Kharagauli National Park (Likani Gate)', 'Cool, quiet pine forest trails into one of Georgia''s largest protected parks, entered from the Likani gate.', 'The national park''s main marked route from here, the Footprint Trail, runs a demanding 13km/6-8hr — too long for most families with young kids — but the first stretch along the Borjomistsqali river out of the Likani guard station makes a genuinely pleasant, shaded, mostly flat forest walk before the trail starts climbing. It''s a low-key contrast to the busier, paid attractions in town: free, quiet, and a good way to actually be in the forest the region is named for rather than just look at it.', 'Free, but you must register for a free safety permit (bring ID) either at the National Park office in Borjomi or the Likani gate before setting out. Stick to the first 1-2km with younger kids and turn back before the climb starts.', 'Morning, before the heat builds', 90, '1.5 hr', NULL, NULL, 'Free', 'Borjomi', 41.826, 43.36, 'Shaded and mostly flat near the gate — a real forest walk without demanding much of little legs, as long as you turn back before the trail climbs.', false, ARRAY['cool', 'walk']::TEXT[], 4, NULL, NULL),
  ('borjomi-bakuriani-green-monastery', 'borjomi-bakuriani', 'Green Monastery (Chitakhevi)', 'A hushed 9th-century forest monastery most Borjomi day-trippers never find, a 45-minute walk from the road.', 'Named for the moss and forest that wrap its stone walls, the Green Monastery (Mtsvane Monastery) sits in the Chitakhevi valley about 12km from Borjomi, tracing back to the 9th century. It''s still an active monastic site, small and unpolished rather than restored-for-tourists, and gets a fraction of the visitors that the town''s mineral park does. The last stretch is on foot along an unpaved forest track, which makes the arrival feel earned rather than just another parking-lot stop.', 'Free. The final approach is roughly 45 minutes on foot each way along an unpaved track — a normal car can get close in dry weather, but check conditions after rain. Modest dress expected as at any active monastery.', 'Morning', 120, '2 hr', NULL, NULL, 'Free', 'Borjomi', 41.810833, 43.309843, 'Frame the walk-in as a hike to a hidden, forgotten monastery — the approach is half the appeal for kids.', false, ARRAY['walk', 'scenic']::TEXT[], 5, NULL, NULL),
  ('borjomi-bakuriani-cafe-iggy', 'borjomi-bakuriani', 'Cafe Iggy', 'A heritage-building restaurant on Kostava Square doing standout Georgian cooking, including Borjomi trout.', 'Opened in 2022 in a restored heritage building, Cafe Iggy is the destination meal in Borjomi rather than just a refuel — known for mini khinkali in pepper sauce and local trout baked in vine leaves with pomegranate sauce. The indoor dining room makes it the region''s most reliable wet-weather option, and it''s central enough to slot in after the park or before heading toward Bakuriani.', 'Fully indoor. Popular at lunch on weekends — arrive by 1pm to avoid a wait, since it doesn''t appear to take phone reservations.', 'Lunch', 90, '1.5 hr', 25, 45, '₾25-45 per person', 'Borjomi', 41.841227, 43.382118, 'Menu has simple grilled and khinkali options kids will actually eat, and an indoor table is a welcome break if they need to sit still for a bit.', false, ARRAY['wine']::TEXT[], 6, NULL, NULL),
  ('borjomi-bakuriani-town-walk', 'borjomi-bakuriani', 'Bakuriani Town & Trinity Church', 'A-frame chalets, pine air, and a tiny hilltop church make for an easy first taste of Bakuriani.', 'Central Bakuriani is small and walkable: wander past the A-frame guesthouses and gear shops, cut through the forested Amirani''s Park, and climb under 10 minutes to the humble Trinity Church, perched on the rim of the extinct Mukhera volcanic crater above town. It''s a low-key, no-agenda way to get oriented before heading to the lifts or slopes, and Amirani''s Park has open ground for kids to run off car-trip energy.', 'Free and open-ended. Amirani''s Park has playgrounds and, in winter, space for sledding and snowman-building.', NULL, 60, '1 hr', NULL, NULL, 'Free', 'Bakuriani', 41.752529, 43.524837, 'Amirani''s Park gives kids room to run (or sled, in winter) right after the drive up — an easy way to burn energy before anything else.', false, ARRAY['walk', 'kids', 'cool']::TEXT[], 7, NULL, NULL),
  ('borjomi-bakuriani-kokhta-cable-car', 'borjomi-bakuriani', 'Kokhta Cable Car', 'A gondola up Mount Kokhta for sunset views and a mountaintop cafe, running through both winter and summer.', 'The same lift network that carries skiers up Mount Kokhta in winter also runs for sightseers, including in summer — a scenic, enclosed ride up through forest to a station with wide views over Bakuriani and the Trialeti range, plus a cafe at the top for a coffee or meal with a view. It requires no fitness at all, which makes it one of the easiest big-payoff views in the whole region.', 'Around 25 GEL return; typically runs roughly 10am-10pm, but summer sightseeing operation on Bakuriani''s lifts has in past years only started in early July — confirm current dates and hours locally before building a day around it.', 'Late afternoon into sunset', 60, '1 hr', 25, 25, '₾25 return', 'Bakuriani', 41.742, 43.548, 'An easy, enclosed cable-car ride with a big view payoff and no walking required.', false, ARRAY['scenic', 'cool', 'evening']::TEXT[], 8, NULL, NULL),
  ('borjomi-bakuriani-alpine-coaster', 'borjomi-bakuriani', 'Didveli Alpine Coaster', 'A gravity-powered rail coaster twisting down the Didveli hillside — Bakuriani''s one real adrenaline hit for kids.', 'This toboggan-style alpine coaster runs on a fixed rail through the forest at the Didveli lift base, with riders controlling their own speed via a hand brake. It''s independent of the ski lifts and, unlike most of the region''s attractions, is built specifically to be repeated — a short, queue-friendly ride that older kids will want to do more than once.', 'Price and which months it runs vary year to year — confirm locally, especially for a summer visit, since operating hours can be limited outside ski season. There''s likely a minimum height or age for solo riders; check at the ticket booth. The fare is charged per ride, not as a day pass.', NULL, 30, '30 min', 15, 30, '₾15-30', 'Bakuriani', 41.728042, 43.531597, 'The single most thrilling five minutes in the region for kids old enough to ride solo; younger kids can usually ride tandem with an adult.', false, ARRAY['thrill', 'kids']::TEXT[], 9, NULL, NULL),
  ('borjomi-bakuriani-skiing', 'borjomi-bakuriani', 'Bakuriani Skiing', 'Georgia''s most family-friendly ski resort, with a dedicated beginner slope and ski schools built for kids.', 'Bakuriani spreads across the Didveli, Kokhta, and Mitarbi areas with around 20 lifts in total, but it''s best known as the easiest place in Georgia to put a beginner — kid or adult — on skis for the first time, thanks to the gentle ''25 Ski Park'' slope and widely available children''s instructors. The 2025/26 season opened Kokhta on Dec 20 and Didveli/Mitarbi on Dec 27, closing Mar 29 — treat those as approximate and confirm the current year''s dates.', 'Day lift pass roughly ₾55 adult / ₾28 for kids 6-12; ticket booths open around 10am-4:45pm. Private lessons run roughly ₾70-100/hr. Renting gear in town is usually cheaper than at the lift base.', 'January-February for the most reliable snow', 240, '4 hr', 28, 55, '₾28-55', 'Bakuriani', 41.7315, 43.528, 'The ''25 Ski Park'' beginner slope and dedicated kids'' instructors make this the easiest first-ever ski day in Georgia.', false, ARRAY['thrill', 'cool']::TEXT[], 10, NULL, NULL),
  ('borjomi-bakuriani-joyland', 'borjomi-bakuriani', 'Joyland Park', 'A snow-tubing and family fun park with zones for toddlers up to bigger kids, right in Bakuriani.', 'Joyland is built squarely for families, split into three zones — Skyland, Tubingland, and Babyland — with tubing runs and rides scaled to different ages, plus an ATV rental kiosk nearby for older kids and adults. It''s primarily a winter, snow-based attraction; some form of it may run in warmer months, but that''s unconfirmed, so it''s a stronger bet for a winter ski trip than a summer one.', 'Primarily a winter (snow-tubing) attraction — summer-season hours and which rides operate then are unconfirmed, so check locally before planning a summer visit around it. What you pay depends on which activities you actually do.', 'Winter', 90, '1.5 hr', 10, 30, '₾10-30', 'Bakuriani', 41.74759, 43.526487, 'Purpose-built for younger kids — the ''Babyland'' zone is aimed at the littlest ones, with tubing runs for older siblings.', false, ARRAY['kids', 'thrill']::TEXT[], 11, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 11.
SELECT count(*) AS borjomi_bakuriani_places
  FROM catalog_places WHERE region_id = 'borjomi-bakuriani';
