-- Migration 10 — Georgia catalog places: Batumi & Adjara
--
-- GENERATED FILE. Source of truth is content/catalog/batumi-adjara.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Black Sea coast & subtropical hills',
  summary       = 'Georgia''s subtropical Black Sea coast: a Belle-Epoque resort city of Art Nouveau facades, a seven-kilometer seaside boulevard and neon nightlife, backed by the green, rain-soaked hills of Adjara. Batumi itself delivers beaches, a cliffside botanical garden and a genuinely distinct cuisine — Adjaruli khachapuri, the boat-shaped cheese bread topped with egg and butter, originates here — while a short drive inland or south along the coast reaches a Roman-era fortress, a border-village beach, and a valley of waterfalls and stone arch bridges. It''s a full multi-day base in its own right, not just a coastal add-on to the rest of Georgia.',
  when_to_go    = 'June through September is peak season: hot, often above 30C, humid, and the boulevard and beaches get genuinely crowded, especially in August. Late spring (May) and early autumn (September-October) are quieter and more comfortable for walking and sightseeing, with the sea still warm enough to swim into October. Adjara has Georgia''s highest rainfall year-round, heaviest in the inland hills — pack a rain layer even for a summer visit, and keep at least one indoor backup (the art museum, a covered restaurant) in your plan regardless of season.',
  getting_there = 'Batumi is roughly 350km from Tbilisi. Driving takes about 5-6 hours via the Tbilisi-Senaki-Batumi highway; the daily direct train takes around 5-6 hours; domestic flights (about an hour in the air) connect Tbilisi and Batumi but add airport time on both ends, so total door-to-door time often lands close to the train. Frequent marshrutkas (minibuses) run from Tbilisi''s Didube station. Within the region, Gonio and Sarpi are a short drive south along the coast road; Mtirala, Makhuntseti and the Tamar Bridge are 30-50 minutes inland up the Acharistsqali valley and need a car or organized tour, since public transport up the valley is thin.',
  base_towns    = 'Batumi is the obvious base — hotels and guesthouses across every budget, and everything on the boulevard and in the old town is walkable. Kobuleti, about 20km north, is a cheaper, quieter beach-town alternative with easy access back into Batumi and toward Mtirala National Park.'
WHERE id = 'batumi-adjara';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('batumi-adjara-boulevard', 'batumi-adjara', 'Batumi Boulevard', 'Seven kilometers of palms, cycle paths and Black Sea views strung along the entire city front.', 'Batumi Boulevard runs the length of the city along the seafront, combining the older 19th-century "Old Boulevard" near the port with a modern 1200-meter extension built in 2009. Palm-lined paths carry cyclists, joggers and evening strollers past fountains, open-air cafes, the Ferris wheel and Alphabet Tower, and long stretches of pebble beach. After dark the boulevard''s dancing fountains run in bursts roughly every hour between 21:00 and 02:00, and the whole strip lights up with the city''s neon skyline. It''s the connective spine of a Batumi visit — you''ll pass through parts of it multiple times rather than visiting it once.', 'Free to walk; rental bikes and electric scooters are available at stands along the route if you want to cover more ground. Midday sun has little shade for long stretches, so early morning or evening is more comfortable in summer.', 'Early morning or after sunset', 90, '1.5 hr', NULL, NULL, 'Free', 'Batumi', 41.653612, 41.634536, 'Playgrounds, wide flat paths for scooters, and ice cream stalls the whole way — an easy win with kids of any age.', false, ARRAY['walk', 'scenic', 'kids']::TEXT[], 1, NULL, NULL),
  ('batumi-adjara-old-town-piazza', 'batumi-adjara', 'Batumi Old Town & Piazza Square', 'Cobbled lanes and Art Nouveau facades around a marble mosaic square at the heart of old Batumi.', 'Piazza Square sits a few streets back from the boulevard, its centerpiece a large marble mosaic floor surrounded by a ring of buildings styled after different European architectural traditions. From there it''s a five-minute walk to Europe Square, anchored by a statue of Medea holding the Golden Fleece, and to the narrow lanes of the old town in between, lined with 19th-century merchant houses, wine bars and street cafes. Both squares also run their own evening fountain shows. It''s a compact, walkable pocket that rewards an unhurried wander rather than a checklist visit.', 'Free to wander. Livelier and cooler in the early evening, when cafe terraces fill up and the fountains at both squares start running.', 'Early evening', 60, '1 hr', NULL, NULL, 'Free', 'Batumi', 41.649594, 41.641122, 'Flat, traffic-free, and full of gelato stalls — an easy stroll for tired legs.', false, ARRAY['walk']::TEXT[], 2, NULL, NULL),
  ('batumi-adjara-art-museum', 'batumi-adjara', 'State Art Museum of Adjara', 'Georgian and Adjaran painting, sculpture and icons indoors — the region''s best answer to a rainy day.', 'This small, central museum on Gorgiladze Street holds a permanent collection of Georgian and Adjaran painting, graphic art, sculpture and religious icons across a manageable handful of rooms. It''s not a destination in itself the way the boulevard or Gonio Fortress are, but it''s genuinely worthwhile and fully indoors, which makes it the natural fallback when Adjara''s rain sets in. Labels are mixed Georgian/English; the collection rewards 45 minutes to an hour rather than a rushed pass-through.', 'Closed Mondays; open 10:00-18:00 the rest of the week. Standard ticket ₾6, ₾7 with a guided excursion; children aged 6-14 pay ₾1 as part of a family ticket, under 6 free.', NULL, 60, '1 hr', 6, 7, '₾6-7 per person', 'Batumi', 41.648622, 41.633863, NULL, false, ARRAY['cool']::TEXT[], 3, NULL, NULL),
  ('batumi-adjara-ali-and-nino', 'batumi-adjara', 'Ali and Nino ("Statue of Love")', 'Two moving metal figures glide together, merge, and pass through one another on the boulevard each evening.', 'Sculptor Tamara Kvesitadze''s kinetic artwork depicts the star-crossed lovers of the novel "Ali and Nino": two 8-meter steel silhouettes that slide toward each other along a track, merge into a single form, and then separate again over roughly a ten-minute cycle. It sits directly on the boulevard near the Alphabet Tower and draws a crowd every evening once it''s dark enough for the lighting to read well. There''s no ticket and no barrier — you simply wait for the cycle if the figures aren''t moving when you arrive.', 'No officially posted schedule; it''s widely reported to start moving from around 7pm and repeat every ten minutes or so through the evening, but timing isn''t guaranteed — if it''s static when you arrive, give it 10-15 minutes or come back after dark.', 'After dark, roughly 7-9pm', 20, '20 min', NULL, NULL, 'Free', 'Batumi', 41.655576, 41.643066, 'Kids get a kick out of watching the two figures "walk through" each other — worth timing your evening around it.', false, ARRAY['evening', 'scenic']::TEXT[], 4, NULL, NULL),
  ('batumi-adjara-chacha-tower', 'batumi-adjara', 'Chacha Tower', 'A clock tower on the boulevard that, at least on paper, once poured chacha from a spout each evening.', 'This 25-meter Ottoman-style clock tower, a deliberate replica of a 1901 landmark in Izmir, was built in 2012 with a novelty feature: a spout designed to run with chacha, Georgia''s grape brandy, for ten minutes each evening. It''s now more a curiosity than a functioning attraction — recent visitor reports describe the clock as stopped and the fountain function as inconsistent or not running, and the stairs to the small observation deck have been reported fenced off. Treat it as a two-minute photo stop on the boulevard rather than something to plan an evening around.', 'Do not count on the chacha fountain running or the tower being open to climb — both are inconsistently reported as non-functional or closed as of recent visits. Confirm locally if either matters to your plans; otherwise it''s a free exterior landmark on the walk along the boulevard.', NULL, 10, '10 min', NULL, NULL, 'Free', 'Batumi', 41.652806, 41.642639, NULL, false, ARRAY['evening']::TEXT[], 5, NULL, NULL),
  ('batumi-adjara-khachapuri-house', 'batumi-adjara', 'House of Adjarian Khachapuri', 'The boat-shaped, egg-topped khachapuri that gave the dish its name, at the spot rated best in the world.', 'Adjaruli khachapuri — an open canoe of bread filled with cheese and topped with a raw egg and a slab of butter that you stir into the melted cheese at the table — originates in this region, and this small, unpretentious restaurant in Old Batumi has been rated the world''s best for it by TasteAtlas. The ritual is simple: tear the crust from the edges, dip it in the molten cheese-egg-butter center, and keep going. A medium khachapuri easily feeds two, and a simple cucumber-tomato salad on the side is the only accompaniment you need.', 'A medium khachapuri runs about ₾18. It''s a small, popular spot with no confirmed reservation system — go hungry and expect a short wait at peak lunch and dinner times. One khachapuri comfortably feeds two people.', NULL, 60, '1 hr', 15, 25, '₾15-25 per person', 'Batumi', 41.645995, 41.633507, 'Rich and filling — one order shared between two kids is usually plenty.', false, ARRAY['wine']::TEXT[], 6, NULL, NULL),
  ('batumi-adjara-botanical-garden', 'batumi-adjara', 'Batumi Botanical Garden', 'Nine world climate zones of subtropical forest tumbling down a seaside cape north of the city.', 'Founded in 1912 by the Russian botanist Andrei Krasnov, this 108-hectare garden covers the cliffs of Mtsvane Kontskhi ("Green Cape") with terraced sections organized by world region — Caucasus, Himalayan, East Asian, Mexican, Australian and more — connected by winding paths with sea views through the trees. It''s large and hilly enough that seeing even a good cross-section takes real time, and the entrance used here is the main southern gate closest to Batumi, not the geographic center of the grounds. An electric buggy service is available for anyone who doesn''t want to walk the whole length.', '₾20 for foreign visitors, ₾10 for Georgian citizens; children under 6 free. Open daily 9:00-17:30 (until 20:00 in summer). Electric buggy hire is roughly ₾10 one-way if you don''t want to walk the entire garden.', 'Morning, before the day heats up', 150, '2.5 hr', 10, 20, '₾10-20', 'Mtsvane Kontskhi', 41.692008, 41.707329, 'Big and hilly with a lot of ground to cover — the electric buggy is worth it with tired kids.', false, ARRAY['walk', 'scenic', 'cool']::TEXT[], 7, NULL, NULL),
  ('batumi-adjara-gonio-fortress', 'batumi-adjara', 'Gonio-Apsaros Fortress', 'Roman-era fortress walls at the mouth of the Chorokhi River, layered with 2,000 years of history.', 'Built as the Roman fortification of Apsaros in the 1st century AD and later held by Byzantine, Genoese and Ottoman garrisons in turn, Gonio''s rectangular perimeter wall — roughly 900 meters around — still stands largely intact, enclosing excavated bath houses, barracks foundations and a small on-site museum. Local tradition holds that the apostle Matthias is buried within the grounds. It''s an easy, mostly flat walk around the walls and interior, with far fewer crowds than anything on the Batumi boulevard.', '₾15 for foreign visitors, ₾10 for Georgian citizens; children under 6 free, ages 6-16 ₾2. Generally open 10:00-18:00, though sources disagree on whether it closes Mondays — confirm locally if visiting off-season.', NULL, 60, '1 hr', 10, 15, '₾10-15 per person', 'Gonio', 41.573264, 41.573816, 'Open walls to climb and a lot of grassy space to run around, but little shade — bring water in summer.', false, ARRAY['walk', 'scenic']::TEXT[], 8, NULL, NULL),
  ('batumi-adjara-sarpi-beach', 'batumi-adjara', 'Sarpi Beach & the Georgia-Turkey Border', 'A pebble beach that runs right up to the border fence, with Turkey visible across the frontier line.', 'Sarpi, about 18km south of Batumi, is Georgia''s southernmost coastal village and sits directly on the border with Turkey — the crossing here operates 24 hours a day. The free public pebble beach runs close enough to the frontier that you can see the checkpoint and Turkish hillside beyond, giving it a novelty most Georgian beaches don''t have, alongside being quieter and less developed than central Batumi''s waterfront. It''s a straightforward add-on to a Gonio Fortress visit rather than a destination on its own.', 'Free, with only a couple of seasonal cafes for facilities — bring your own water and shade. This is an active border zone: stay on the beach and don''t approach or photograph the checkpoint itself.', NULL, 45, '45 min', NULL, NULL, 'Free', 'Sarpi', 41.523659, 41.548288, 'Pebble beach rather than sand — water shoes make it much more comfortable.', false, ARRAY['water']::TEXT[], 9, NULL, NULL),
  ('batumi-adjara-mtirala-national-park', 'batumi-adjara', 'Mtirala National Park', 'Georgia''s wettest national park: a rainforest-green ridge with a real day hike to a waterfall and a lake.', 'Mtirala — "the crying one" — is named for having the highest rainfall in Georgia, and the payoff is dense, permanently green Colchic mixed forest draped over steep inland ridges southeast of Batumi. The visitor center and trailhead sit in the village of Chakvistavi; the main marked trail climbs through the forest to a waterfall and a small lake, a genuine half-day hike rather than a short walk. A short zipline near the visitor center offers a lighter-effort taste of the park for anyone not up for the full trail.', 'Entrance to the park is free; the waterfall-and-lake trail is a real hike, roughly 7km round trip and 3.5-4 hours — budget accordingly and wear proper shoes. A short zipline near the visitor center runs roughly ₾15-20. The access road from Chakvi is narrow and partly unpaved, so drive it slowly.', 'Morning start, to have daylight margin for the full trail', 240, '4 hr', NULL, NULL, 'Free', 'Chakvi', 41.680078, 41.860252, 'The full hike is long for young kids; the visitor-center area and short zipline are a better match for younger children.', false, ARRAY['hike', 'water']::TEXT[], 10, NULL, NULL),
  ('batumi-adjara-makhuntseti-waterfall', 'batumi-adjara', 'Makhuntseti Waterfall', 'A 48-meter curtain of water dropping into a plunge pool, barely a hundred meters off the Keda road.', 'Near the village of Zeda Makhuntseti in Keda municipality, about 30km and under an hour from Batumi up the Acharistsqali valley, this waterfall is one of the tallest in Adjara and one of the easiest to reach — a short, flat walk from roadside parking brings you straight to a viewing point at the base. Roadside stalls sell local honey and fruit, especially in the warmer months. It''s typically paired with the Queen Tamar arch bridge a short distance further up the same road.', 'No entrance fee; roadside parking costs about ₾2. Visit alongside the Queen Tamar Bridge just up the valley rather than as a standalone stop — budget time for both.', NULL, 30, '30 min', NULL, NULL, 'Free', 'Makhuntseti', 41.574938, 41.858308, 'Flat, short walk right to the viewing point — easy going with kids.', false, ARRAY['water', 'walk']::TEXT[], 11, NULL, NULL),
  ('batumi-adjara-tamar-bridge', 'batumi-adjara', 'Queen Tamar''s Arch Bridge, Makhuntseti', 'A single stone arch over the Acharistsqali gorge, named for the queen of Georgia''s medieval golden age.', 'This medieval single-span stone bridge, roughly 20 meters long and 6 meters above the Acharistsqali river, carries the name of Queen Tamar, whose 12th-13th century reign is remembered as Georgia''s golden age, though the bridge''s exact construction date is disputed. It sits a short distance up the valley road from Makhuntseti Waterfall, with small cafes and a roadside winery nearby. Walk out onto the arch itself, then down to the riverbank below for the classic view of the span framed by the gorge.', 'Free to walk onto the bridge; roadside parking costs about ₾2. Visit together with Makhuntseti Waterfall just downstream rather than as a separate trip.', NULL, 25, '25 min', NULL, NULL, 'Free', 'Makhuntseti', 41.571021, 41.860057, 'Low walls in places on the arch itself — hold hands near the edges.', false, ARRAY['scenic', 'walk']::TEXT[], 12, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 12.
SELECT count(*) AS batumi_adjara_places
  FROM catalog_places WHERE region_id = 'batumi-adjara';
