-- Migration 10 — Georgia catalog places: Mtskheta & the Military Highway
--
-- GENERATED FILE. Source of truth is content/catalog/mtskheta.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Ancient capital, the road north',
  summary       = 'Georgia''s ancient capital and spiritual center, just 20 minutes from Tbilisi, paired with the opening stretch of the Georgian Military Highway as it follows the Aragvi River north to the turquoise Zhinvali reservoir and Ananuri fortress. Two UNESCO cathedrals sit alongside a quieter cave-monastery, a genuine destination meal, and a paddle or raft on the water. This is a full, satisfying day (or two) without committing to the longer push toward Gudauri and Kazbegi.',
  when_to_go    = 'Year-round — unlike the high passes further north, this lower stretch rarely closes for weather. In summer, aim to be inside Jvari or Svetitskhoveli before 10am to beat both the heat and the tour-bus crush. Water activities (rafting and kayaking) run roughly mid-April through mid-October only, so check dates if visiting outside summer.',
  getting_there = 'Mtskheta is 20-25 min (~20 km) from Tbilisi via the Mtskheta Highway (S1), on good tarmac the whole way. Ananuri and the Zhinvali reservoir add another 40-45 min further north on the paved, well-maintained Georgian Military Highway (E117) — no 4x4 needed for this segment. Marshrutkas run from Tbilisi''s Didube station to Mtskheta (~30 min, a couple of GEL); getting on to Ananuri or Zhinvali by public transport is thin, so a car, taxi, or organized tour is the practical option.',
  base_towns    = 'Almost everyone day-trips from Tbilisi — it''s genuinely close enough that basing here isn''t necessary. Mtskheta itself has a handful of small guesthouses if you''d rather overnight, which buys you an early start before the tour buses arrive at Jvari and Svetitskhoveli.'
WHERE id = 'mtskheta';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('mtskheta-old-town', 'mtskheta', 'Mtskheta Old Town Wander', 'Cobbled lanes, churchkhela stalls, and the river confluence Georgians consider sacred ground.', 'Wander the pedestrianized lanes around Svetitskhoveli, lined with wine cellars, souvenir stalls, and outdoor cafes selling churchkhela. Head down toward the riverbank for a look at where the Aragvi meets the Mtkvari (Kura) — the same confluence you''ll see from above at Jvari. It''s flat, partly shaded, and the closest thing to a relaxed stroll-and-snack break in the region.', 'Free to wander; parking fills by mid-morning in high season, so arrive early or plan for a short walk in from a lot.', 'Late afternoon, after the day-trip buses have left', 45, '45 min', NULL, NULL, 'Free', 'Mtskheta', 41.845, 44.7185, 'Flat and easy for little legs, with plenty of ice cream and churchkhela stalls to bribe with.', false, ARRAY['walk', 'kids']::TEXT[], 1, NULL, NULL),
  ('mtskheta-svetitskhoveli', 'mtskheta', 'Svetitskhoveli Cathedral', 'Georgia''s holiest cathedral, said to hold Christ''s robe, and still the seat of the Georgian church.', 'This 11th-century UNESCO-listed cathedral is the spiritual heart of the Georgian Orthodox Church, built on the site where, legend holds, Christ''s robe was buried. Step inside for the soaring stone interior, faded frescoes, and royal tombs, including several Bagrationi kings. The walled courtyard around it is part of the same complex and worth a slow circuit. It''s a working church, so expect services, incense, and the occasional wedding or baptism in progress.', 'Cover shoulders and knees — wraps are usually available to borrow at the door. Busiest 11am-2pm with tour groups; go before 10am or after 4pm. Free, but donations are welcomed.', 'Before 10am, or after 4pm', 40, '40 min', NULL, NULL, 'Free', 'Mtskheta', 41.8455, 44.7191, 'Interesting even for kids who normally balk at churches — giant stone pillars, royal tombs, and a carved dragon fresco give you things to point at.', false, ARRAY['scenic', 'walk']::TEXT[], 2, NULL, NULL),
  ('mtskheta-samtavro', 'mtskheta', 'Samtavro Convent', 'A quieter 4th-century convent two minutes from the cathedral, where Georgia''s first Christian king is buried.', 'Samtavro traces back to where St. Nino lived after bringing Christianity to Georgia in the 4th century, but sits just a few minutes'' walk from Svetitskhoveli and gets a fraction of the visitors. Inside the walled complex are the 11th-century Transfiguration Church, a smaller church of St. Nino, and the graves of King Mirian and Queen Nana, Georgia''s first Christian royals. It''s a working convent — nuns tend the grounds — and noticeably calmer than the main cathedral next door. A good option when Svetitskhoveli feels overrun with tour groups.', 'Free entry; modest dress expected as at any active church. It''s the site most visitors miss rather than the reverse — worth the extra 20 minutes if you have them.', NULL, 20, '20 min', NULL, NULL, 'Free', 'Mtskheta', 41.8479, 44.7201, NULL, false, ARRAY['walk']::TEXT[], 3, NULL, NULL),
  ('mtskheta-jvari', 'mtskheta', 'Jvari Monastery', 'Hilltop monastery framing Georgia''s most photographed view: two rivers meeting far below.', 'Perched on a ridge above the confluence of the Mtkvari and Aragvi rivers, this 6th-century monastery is one of Georgia''s oldest surviving churches and the view behind half its postcards. The small stone church itself takes only a few minutes to see; the real draw is the panorama over Mtskheta and the valley. It gets crowded with tour buses by mid-morning, and the single viewpoint bottlenecks fast. Go early or at golden hour for better light and more room to breathe.', 'Free; no shade at the viewpoint, so bring hats and water in summer. Modest dress required inside the church. Tour buses arrive from around 10:30am onward.', 'Before 10am, or golden hour', 30, '30 min', NULL, NULL, 'Free', 'Mtskheta', 41.8383, 44.7331, 'The view is the payoff, not the church interior — good for restless kids who''d rather be outside than in another cathedral.', false, ARRAY['scenic']::TEXT[], 4, NULL, NULL),
  ('mtskheta-shio-mgvime', 'mtskheta', 'Shio-Mgvime Monastery', 'A cave-monastery tucked into a limestone canyon that most day-trippers never find.', 'Founded in the 6th century by the monk Shio, who lived as a hermit in a cave here, this monastery sits in a narrow, dramatic canyon about 8 km from Mtskheta and sees a fraction of Jvari''s crowds. Wander the terraced complex, peer into Shio''s original cave cell, and follow the path up the canyon wall for a quiet valley view. Monks and nuns still live and work the grounds, so keep voices down. The unpaved access road is fine for a normal car taken slowly.', 'No entrance fee (donations welcome); modest dress required, including headscarves for women. No cafe on site — bring water. It''s an active monastic community, not a signposted tourist site, so visits should stay quiet.', 'Morning', 50, '50 min', NULL, NULL, 'Free', 'Mtskheta', 41.8625, 44.6403, 'The cave cell and canyon setting tend to land better with kids than another cathedral interior — frame it as a monk''s hideout.', false, ARRAY['cave', 'scenic', 'walk']::TEXT[], 5, NULL, NULL),
  ('mtskheta-mukhrani', 'mtskheta', 'Chateau Mukhrani', 'A restored royal winery estate with underground cellars and a proper indoor restaurant.', 'Chateau Mukhrani is a restored 19th-century estate of the Bagrationi-Mukhrani royal family, about 20 minutes from Mtskheta, built in a French-chateau style with formal gardens and a working winery beneath it. Walk the grounds for free, or take the short guided tour through the underground cellar, finishing with a tasting of four estate wines. The on-site restaurant serves a full Georgian menu indoors, making this the region''s best fallback when the weather turns. Book the tasting ahead in peak season; the grounds and restaurant don''t need reservations.', 'Grounds are free to walk; the cellar tour plus tasting runs roughly ₾35 per person. Book the tasting slot ahead on weekends. Restaurant and cellar are fully indoor/covered — a genuine wet-weather option.', 'Late morning or lunchtime', 90, '1.5 hr', 15, 35, '₾15-35 (grounds free; cellar tour ₾15; tour + tasting ~₾35)', 'Mukhrani', 41.942, 44.5814, 'Grounds and gardens are easy for kids to run around; the cellar tasting is an adult interest, but the restaurant has kid-friendly Georgian staples.', true, ARRAY['wine', 'cool', 'kids']::TEXT[], 6, NULL, NULL),
  ('mtskheta-salobie-bode', 'mtskheta', 'Salobie Bode', 'Clay-pot bean stew (lobio) that locals and every guidebook agree is the best in the country.', 'Salobie Bode has been serving lobio — beans slow-baked in individual clay pots with cornbread (mchadi) — since long before Mtskheta was a tourist stop, and it''s still the reason to eat here rather than just refuel. Portions are enormous, prices are low, and the beer-garden-style outdoor seating fills with as many locals as visitors. Order the lobio, a plate of khinkali, and mtsvadi (grilled meat) to share family-style. It sits just south of the old town on the way in or out of Mtskheta, so it''s an easy detour rather than a special trip.', 'Cash is the safe bet — card acceptance is inconsistent. Busy at lunch on weekends; arrive by 12:30 to beat the rush. Seating is outdoor with limited shelter, so pair a rainy day with Chateau Mukhrani instead.', 'Lunchtime, before 1pm', 60, '1 hr', 20, 30, '₾20-30 per person', 'Mtskheta', 41.8285, 44.72529, 'Big shareable portions and a relaxed, noisy atmosphere — no need for quiet-restaurant behavior.', false, ARRAY['wine']::TEXT[], 7, NULL, NULL),
  ('mtskheta-zhinvali-kayak', 'mtskheta', 'Zhinvali Reservoir Kayaking', 'Calm, swimmable turquoise water on the Zhinvali reservoir — the region''s easiest cool-off.', 'The Aragvi Adventure Center, on the wooded bank where the Pshavis Aragvi river meets the Zhinvali reservoir, rents kayaks and canoes for a gentle paddle on genuinely turquoise, swimmable water. It''s calm rather than technical — a good fit for nervous paddlers or younger kids who''d find the rafting a step too far. The center also has a playground, volleyball court, and a short zipline if the water alone isn''t enough. It only operates mid-April through mid-October, so this isn''t a shoulder-season option.', 'Open mid-April to mid-October only — confirm before planning an off-season visit. Confirm the current rental price on arrival; rates are set by the operator and can shift season to season. Bring a change of clothes.', 'Midday, when the water is warmest', 120, '2 hr', 40, 60, '₾40-60 per person (confirm on-site)', 'Zhinvali', 42.2205, 44.8321, 'The calmest water option in the region — swimmable, shallow near the bank, and life jackets provided.', false, ARRAY['water', 'kids', 'cool']::TEXT[], 8, NULL, NULL),
  ('mtskheta-aragvi-rafting', 'mtskheta', 'Aragvi River Rafting', 'A gentle grade II-III float down the Aragvi — thrilling for kids without scaring the grown-ups.', 'The same Aragvi Adventure Center runs half-day rafting trips on the Aragvi, with certified guides, life jackets, and helmets included. Water is highest and roughest (grade III-IV) during May-June snowmelt; by August and September it settles to a family-friendly grade II, the sweet spot for this itinerary. Trips typically run 1.5-2 hours on the water in a 6-8 seat raft, often paired with a riverside barbecue lunch. It only runs mid-April through mid-October, so check dates if traveling outside summer.', 'Runs mid-April to mid-October only. Book ahead for peak summer weekends. Most operators set a minimum age (commonly around 8-10) — confirm this when booking if traveling with younger kids. Bring a dry bag for phones and cash.', 'Late summer (Aug-Sep), when the river is calmest', 150, '2.5 hr', 120, 180, '₾120-180 per person', 'Zhinvali', 42.2205, 44.8321, 'Genuinely thrilling for kids but graded gentle by August; check the operator''s minimum age before booking.', true, ARRAY['water', 'thrill', 'kids']::TEXT[], 9, NULL, NULL),
  ('mtskheta-ananuri', 'mtskheta', 'Ananuri Fortress', 'A 17th-century fortress-church complex rising straight out of the turquoise Zhinvali reservoir.', 'Ananuri''s stone towers and twin churches sit directly on the reservoir shore, making it one of the most photographed stops on the Military Highway. Climb the fortress walls and tower for a view over the water, then step inside the churches to see the carved stone facades and frescoed interiors. The complex is compact, but the climbing — steep, uneven stone stairs, low doorways — makes it more physical than the free churches back in Mtskheta. Food stalls and viewpoint pull-offs line the road just outside, good for a snack or photo before continuing north.', 'Free entry; modest dress for the churches. Stairs inside the towers are steep, uneven, and unguarded in places — supervise kids and wear real shoes, not sandals. Gets crowded with tour buses at midday.', 'Morning or golden hour', 45, '45 min', NULL, NULL, 'Free', 'Ananuri', 42.1633, 44.6967, 'Kids love climbing the tower, but the stairs are steep and unguarded in places — hold hands on the way down.', false, ARRAY['scenic', 'water', 'walk']::TEXT[], 10, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 10.
SELECT count(*) AS mtskheta_places
  FROM catalog_places WHERE region_id = 'mtskheta';
