-- Migration 10 — Georgia catalog places: Kutaisi & Imereti
--
-- GENERATED FILE. Source of truth is content/catalog/kutaisi-imereti.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Caves, canyons & water',
  summary       = 'Georgia''s second city and its western hinterland: lit stalactite caves, a cliffside canyon walkway, turquoise canoe water, and two UNESCO-era monasteries within a short drive of each other. Kutaisi itself adds an old-town evening of a river bridge, a gilded fountain, and one of the best tables in the west. Note that Martvili Canyon — the classic pairing with a Kutaisi day trip — actually sits over the border in Samegrelo; it''s included here because that''s how virtually everyone visits it, not because it''s geographically Imereti.',
  when_to_go    = 'Genuinely year-round — Prometheus Cave and Sataplia are open daily, indoors, and cool, making them the region''s answer to both summer heat and rain. Okatse''s hanging walkway and Martvili''s canyon path close outright in rain or snow for safety, so build a backup day if you''re visiting outside the reliable April-October season. Kinchkha and Okatse are shoulder-season prettiest in spring when the rivers run fuller. Avoid assuming a Monday closure here — unlike many Georgian sites, Prometheus, Sataplia and Okatse are all open seven days a week.',
  getting_there = 'Kutaisi is 220-240 km from Tbilisi, 4-4.5 hours by car on the E60/S1 highway (good tarmac throughout, including the Rikoti Pass tunnel corridor). A daily fast train covers the same route in about 5 hours; marshrutkas run regularly from Tbilisi''s Didube station (~4.5 hr). Kutaisi International Airport also has direct low-cost flights from several European cities, which makes this region a common start or end point for a wider Georgia loop rather than a pure day trip from Tbilisi. Once in the region, the canyon and cave sites are 30-70 minutes apart by car in different directions — a rented car or driver is the practical way to link more than one or two in a day.',
  base_towns    = 'Kutaisi is the obvious base — central to everything here, with the widest range of hotels and restaurants, and close enough to Gelati, Motsameta and Bagrati to visit on foot or a short taxi ride. Plan on two nights if you want to cover the caves/canyons axis (Prometheus, Sataplia, Okatse, Kinchkha), the Martvili detour, and the monasteries without rushing any of them.'
WHERE id = 'kutaisi-imereti';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('kutaisi-imereti-prometheus-cave', 'kutaisi-imereti', 'Prometheus Cave', 'A 1.4km lit stalactite gallery through six chambers, ending in an optional underground boat ride.', 'Prometheus (Kumistavi) Cave is one of Georgia''s largest show caves, with a paved, lit 1.4 km walking route through six of its many chambers, past stalactites, stalagmites, and small underground pools, with classical music piped in along the way. A guide (included in the ticket) walks the group through and explains the formations. At the far end, an optional boat ride floats you roughly 280 m along the underground river back toward the exit — genuinely atmospheric, though short. The boat is suspended after heavy rain when the river runs high, so it isn''t guaranteed even if you pay for it.', 'Open every day of the year, no closing day. The boat is a separate ticket on top of entrance and is sometimes cancelled after rain — ask at the ticket counter before paying for it. Ticket price includes a Georgian/English/Russian-speaking guide.', NULL, 120, '2 hr', 40, 70, '₾40-70', 'Tsqaltubo', 42.376641, 42.600845, 'Cool, flat, and lit throughout — an easy win for kids, and the boat ride at the end feels like a mini theme-park moment.', false, ARRAY['cave', 'cool', 'kids', 'scenic']::TEXT[], 1, NULL, NULL),
  ('kutaisi-imereti-sataplia', 'kutaisi-imereti', 'Sataplia Nature Reserve', 'Real Cretaceous dinosaur footprints under glass, a short cave, and a glass panoramic platform over Imereti.', 'Sataplia protects a set of genuine dinosaur tracks preserved in limestone, displayed under a protective pavilion as the reserve''s headline attraction. From there a guided loop leads through a small karst cave with colored lighting, a stretch of relict Colchic forest, and out to a glass-floored panoramic terrace looking over the Kutaisi lowlands. It''s compact and entirely guided — you can''t wander off-route — which keeps the whole visit tight and family-friendly.', 'Open every day, 10:00-17:00, no closing day — the panoramic walkway simply closes in rain or snow for safety. Foreign-adult tickets run well above the resident rate; bring ID if you qualify for the local price. Children aged 6-18 pay ₾5.50, and under-6s are free.', NULL, 75, '1 hr 15 min', 30, 30, '₾30', 'Kutaisi', 42.316167, 42.672667, 'The dinosaur footprints are the highlight for young kids — genuine tracks under glass, not replicas.', false, ARRAY['cave', 'kids', 'scenic']::TEXT[], 2, NULL, NULL),
  ('kutaisi-imereti-okatse-canyon', 'kutaisi-imereti', 'Okatse Canyon', 'A steel walkway clipped to a cliff face, 100m above a river gorge, in Khoni''s Dadiani forest.', 'Okatse''s hanging trail is a 780 m steel walkway bolted directly into the canyon wall, with sections of mesh or glass flooring so you''re looking straight down into the gorge. Getting there is part of the visit: it''s roughly 2.3 km from the visitor centre through forest to the trailhead, walkable or covered by a shuttle van for a fee. Reviewers regularly compare the exposure and drop to something out of an adventure film — genuinely dramatic rather than a token viewpoint.', 'Budget for the approach walk, not just the walkway itself — most of the visit is the 2.3 km each-way trail through the forest before you even reach the hanging section. Closed to walkers outright in rain or snow. Entrance is ₾20 for foreigners (₾12 residents); the shuttle van is a separate, informally-priced service — confirm the fare on arrival rather than assuming a number. Children aged 6-18 pay ₾5.50.', 'Morning, before tour groups arrive from Kutaisi', 150, '2.5 hr', 20, 20, '₾20', 'Gordi', 42.451306, 42.550056, 'Thrilling but genuinely exposed on a mesh/glass walkway high above the gorge — good for confident kids, not toddlers or anyone uneasy with heights.', false, ARRAY['cave', 'hike', 'scenic']::TEXT[], 3, NULL, NULL),
  ('kutaisi-imereti-kinchkha-waterfall', 'kutaisi-imereti', 'Kinchkha Waterfall', 'A three-tier, 130m cascade reached by a quiet forest trail most Kutaisi day-trippers skip entirely.', 'Kinchkha (also called Okatse Waterfall) drops in three stages — roughly 25 m, 70 m, and 35 m — down a forested valley near Okatse Canyon, in the same Khoni municipality. A marked ~2.1 km trail from Kinchkha village leads to the viewing point; it sees a fraction of Okatse''s crowds despite sitting close by. This is the region''s clearest "most visitors miss it" stop — worth the extra detour if you already have a driver out this way.', 'No entrance fee currently. It''s near Okatse but is a separate stop with its own trailhead and parking, not a shared ticket — plan the extra time rather than assuming a quick add-on. The forest path gets muddy after rain, so wear real shoes.', NULL, 90, '1.5 hr', NULL, NULL, 'Free', 'Khoni', 42.495639, 42.550528, 'The walk is longer and less built-up than Okatse''s — fine for kids who like a forest hike, less practical with a stroller.', false, ARRAY['water', 'walk', 'scenic']::TEXT[], 4, NULL, NULL),
  ('kutaisi-imereti-martvili-canyon', 'kutaisi-imereti', 'Martvili Canyon', 'A narrow limestone gorge with water so turquoise it looks dyed, floated by canoe past mossy cliffs.', 'Martvili''s canyon walk follows a walkway along the rim and floor of a narrow gorge cut by the Abasha River, past small waterfalls and pools of striking turquoise-green water. The highlight is the roughly 20-minute canoe/boat section through the most dramatic stretch of the gorge — the walking loop alone is short and most people are really here for the water. Technically this sits in Samegrelo, not Imereti, about 1-1.5 hours from Kutaisi, but it''s included here because it''s the day trip virtually every Kutaisi-based visitor actually takes, usually paired with Prometheus Cave or Okatse.', 'Geography note: Martvili is in Samegrelo region, not Imereti — don''t be surprised if other sources file it separately. Open 10:00-18:00 (summer, last entry 17:30); winter hours start later. The boat/canoe ride is a separate ~₾20 add-on and can queue up badly in summer; a separately-operated zipline (₾50-100) is available too.', 'Weekday morning, before tour buses arrive', 90, '1.5 hr', 20, 40, '₾20-40', 'Martvili', 42.45856, 42.37752, 'The canoe section is calm, life-jacketed water — a highlight for kids, though the boat queue can run long in peak summer.', false, ARRAY['cave', 'water', 'scenic', 'kids']::TEXT[], 5, NULL, NULL),
  ('kutaisi-imereti-gelati-monastery', 'kutaisi-imereti', 'Gelati Monastery', 'King David the Builder''s 12th-century monastery and academy — still on the UNESCO list, still under scaffolding.', 'Founded in 1106 by David IV, Gelati was both a monastery and one of the era''s great centers of learning, and its main cathedral holds a celebrated 12th-century mosaic of the Virgin along with extensive frescoes. Unlike Bagrati Cathedral in town, Gelati remains on UNESCO''s World Heritage list. It is, however, in the middle of a long-running restoration: parts of the main church''s facade and interior are behind scaffolding, though the apse mosaic and most frescoes remain visible. The complex also includes smaller churches and King David''s own tomb at the gate, by tradition placed so visitors would walk over it.', 'Free entry, open daily (roughly 9am-7pm, though hours have been reported as inconsistent during restoration work). Expect scaffolding on parts of the main cathedral — it doesn''t block the mosaic or most frescoes, but it does affect photos. Modest dress required as at any active church.', 'Morning, paired with Motsameta on the same road', 50, '50 min', NULL, NULL, 'Free', 'Kutaisi', 42.29472, 42.76806, NULL, false, ARRAY['scenic', 'walk']::TEXT[], 6, NULL, NULL),
  ('kutaisi-imereti-motsameta-monastery', 'kutaisi-imereti', 'Motsameta Monastery', 'A cliff-edge monastery over the Tskaltsitela gorge, where locals crawl under a martyrs'' shrine for luck.', 'Motsameta sits on a dramatic promontory above a bend in the Tskaltsitela (''Red Water'') river, named for two 8th-century Georgian dukes martyred here by Arab invaders. Inside, the ark holding their relics sits on a raised platform; local tradition holds that circling it three times and ducking under a low tunnel beneath it — without touching the walls or ceiling — grants a wish. It gets a fraction of Gelati''s visitors despite being only a few minutes down the same road, and the canyon-edge setting is arguably the more striking view of the two.', 'Free entry, open roughly 8am-8pm daily. Most day trips skip it in favor of Gelati next door — that''s exactly what makes it the quieter of the two.', NULL, 30, '30 min', NULL, NULL, 'Free', 'Kutaisi', 42.28194, 42.75917, 'The crawl-under-the-shrine tradition is a fun, harmless bit of ritual for kids to try.', false, ARRAY['scenic', 'walk']::TEXT[], 7, NULL, NULL),
  ('kutaisi-imereti-bagrati-cathedral', 'kutaisi-imereti', 'Bagrati Cathedral', 'An 11th-century cathedral rebuilt so completely in 2012 that it cost Georgia its UNESCO listing.', 'Bagrati crowns a hill over central Kutaisi and the Rioni River, and remains an active cathedral — seat of the Metropolitan of Kutaisi and a popular local wedding venue. Its full-scale reconstruction, completed in 2012 after the medieval structure stood largely as a ruin for centuries, was judged by UNESCO to have compromised its authenticity so severely that the site was permanently removed from the World Heritage list in 2017; unlike neighboring Gelati, it has not been relisted. Visit for the hilltop view over the city and river rather than for original medieval fabric — most of what stands today is 21st-century reconstruction.', 'Free entry. It''s a working cathedral, so modest dress and quiet are expected, especially on weekends when weddings are common. Worth knowing before you go: this is a reconstruction, not the original 11th-century building.', 'Golden hour, for the view over the Rioni', 30, '30 min', NULL, NULL, 'Free', 'Kutaisi', 42.2773, 42.7043, NULL, false, ARRAY['scenic', 'walk']::TEXT[], 8, NULL, NULL),
  ('kutaisi-imereti-katskhi-pillar', 'kutaisi-imereti', 'Katskhi Pillar', 'A tiny monastery perched atop a 40m limestone pillar, viewable only from the ground since climbing was restricted.', 'Near Chiatura, a single limestone pillar rises about 40 m from the valley floor, topped by a small church that a resident monk has occupied since the 1990s. Climbing the pillar has been restricted to the monk and clergy since 2018 — visitors cannot go up, even on a guided basis. What you actually do here is view the pillar from the base church of Simeon Stylites and the surrounding cave complex at ground level; the strange silhouette against the sky is the whole point, not an ascent.', 'You cannot climb the pillar or visit the summit chapel under any circumstances — that''s monks-only. Everything visitable is at ground level: the base church and nearby caves. It''s roughly 1.5-2 hours from Kutaisi via Chiatura, whose old Soviet cable cars are worth a stop in their own right if you''re already out this way.', NULL, 45, '45 min', NULL, NULL, 'Free', 'Chiatura', 42.2875, 43.2156, 'No climbing involved for visitors, so it''s an easy stop — the appeal for kids is mostly the ''how do the monks even live up there'' story.', false, ARRAY['scenic', 'walk']::TEXT[], 9, NULL, NULL),
  ('kutaisi-imereti-old-town', 'kutaisi-imereti', 'Kutaisi Old Town: White Bridge & Colchis Fountain', 'An evening stroll over the Rioni''s pedestrian White Bridge, ending at a fountain of gilded Colchian animals.', 'Kutaisi''s White Bridge is a pedestrian crossing over the Rioni River linking the old town to the riverside promenade, lined with cafes that fill up as the evening cools. A short walk away, Colchis Fountain in the central square is decorated with gilded replicas of the animal and figurine motifs from the region''s famous Colchian gold hoards, lit up after dark. Neither site takes long individually, but together with the surrounding lanes they make the natural place to end a day out at the canyons and caves.', 'Free to wander. Best after sunset, when both the bridge and the fountain are lit — daytime is fine but doesn''t show off either landmark as well.', 'Evening, after dinner', 60, '1 hr', NULL, NULL, 'Free', 'Kutaisi', 42.268748, 42.700381, 'Flat, pedestrian-only, and lively in the evening — easy with kids in tow, with ice cream stalls along the way.', false, ARRAY['walk', 'evening', 'kids']::TEXT[], 10, NULL, NULL),
  ('kutaisi-imereti-palaty', 'kutaisi-imereti', 'Palaty', 'A two-floor old-town institution serving clay-pot pelmeni, walnut-and-pomegranate kuchmachi, and the city''s best lobiani.', 'Tucked behind an easy-to-miss doorway near the White Bridge, Palaty is a longstanding Kutaisi favorite that doubles as a wine bar with a solid list of Georgian ambers and reds. The ground floor has a romantic, sometimes live-jazz atmosphere; upstairs is brighter and more casual. Order the Siberian-style pelmeni baked and sealed in a clay pot, the kuchmachi (liver and heart with walnuts and pomegranate), and the Imeretian lobiani — regularly cited as the best bean bread in the city — alongside an Adjarian khachapuri to share.', 'The entrance is genuinely easy to miss — look for the wood doorway under the arches near the White Bridge and follow the stairs up to the dining floors. It draws both locals and tour groups, so reserve ahead for dinner in high season if you can.', 'Dinner, or lunch to beat the evening crowd', 90, '1.5 hr', 30, 60, '₾30-60 per person', 'Kutaisi', 42.268896, 42.702041, 'Big shareable plates and a relaxed two-floor layout suit kids fine, though the ground-floor live-jazz nights skew toward an adult evening vibe.', false, ARRAY['wine', 'evening']::TEXT[], 11, NULL, NULL),
  ('kutaisi-imereti-baias-wine', 'kutaisi-imereti', 'Baia''s Wine', 'A family qvevri winery in the Imereti hills where the tasting comes with a full home-cooked Imeretian meal.', 'Run by siblings Baia, Gvantsa, and Giorgi Abuladze in the village of Meore Obcha near Baghdati, Baia''s Wine is a small, low-intervention winery working with indigenous Imereti grapes — Tsitska, Tsolikouri, Krakhuna, Otskhanuri Sapere, and Aladasturi — fermented in traditional qvevri. A visit is a guided walk through the vineyard and cellar with the family, followed by a seated tasting of several qvevri wines, often paired with home-cooked Imeretian food. Everything happens indoors or under cover once you''re past the vineyard walk, which makes it the region''s best rainy-day pivot once you''ve had your fill of the show caves.', 'This is a small family operation that runs on advance booking — don''t plan on walking in. Tasting-only is roughly ₾70 per adult (₾40 for children under 12); the fuller wine-and-dine experience with a home-cooked meal costs more and is often booked as a package with transport included, so confirm the exact price and what''s included when you book.', 'Lunch or early afternoon', 150, '2.5 hr', 40, 70, '₾40-70', 'Baghdati', 42.123031, 42.896887, 'A working winery visit, not built for kids — the cellar walk and seated tasting run long for younger children.', true, ARRAY['wine', 'cool']::TEXT[], 12, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 12.
SELECT count(*) AS kutaisi_imereti_places
  FROM catalog_places WHERE region_id = 'kutaisi-imereti';
