-- Migration 10 — Georgia catalog places: Svaneti
--
-- GENERATED FILE. Source of truth is content/catalog/svaneti.json.
-- Regenerate with: node scripts/build-catalog-sql.mjs
-- Do not hand-edit — your changes will be overwritten.
--
-- Run in Supabase Dashboard > SQL Editor after migration-09. Idempotent:
-- re-running is a no-op, and it will not overwrite an edited row.

UPDATE catalog_regions SET
  subtitle      = 'Medieval towers under big mountains',
  summary       = 'Georgia''s most dramatic highland region: stone defensive towers rising straight out of villages under 5,000m peaks, reachable only by a long flight or road journey that is itself part of the trip. Mestia is the region''s hub — a walkable old quarter, an enterable Svan tower-house, and a proper museum for the days weather closes everything else down. Ushguli, one of Europe''s highest continuously inhabited settlements, anchors a full day trip along a road that has only recently become drivable without a dedicated 4x4. Add a glacier hike, a ropeway panorama, and a valley walk to the foot of Shkhara and there''s real variety packed into what is otherwise a genuinely remote corner of the country.',
  when_to_go    = 'Late June through September is the only fully reliable window — this is by far the most weather- and season-restricted region in this catalog. Outside those months the Mestia-Ushguli road, the high hiking trails, and the Zuruldi ropeway are frequently snowbound, closed, or simply not worth the risk, and several Svan villages are effectively cut off in winter. Even in season, plan morning starts: cloud and storms tend to build over the peaks by early afternoon, and both the ropeway and the Ushguli day trip depend on visibility and road conditions holding.',
  getting_there = 'Svaneti is the most remote region in this catalog, and getting there is its own undertaking. By road from Tbilisi: Tbilisi to Zugdidi is 5-6 hours by car or marshrutka, then Zugdidi to Mestia is a further roughly 3 hours on a since-rebuilt, mostly paved road through the Jvari Pass tunnels — call it 8-9 hours door to door. A direct daily marshrutka also runs from Tbilisi''s Navtlugi station at 07:00 (about 9-10 hours, roughly ₾50); the old overnight Tbilisi-Zugdidi train has been discontinued, so the full journey is now done by road. The alternative is flying: Vanilla Sky operates small 17-seat Twin Otter aircraft from Natakhtari, near Tbilisi, to Mestia in about 40 minutes, but these are visual-flight-rule flights that are frequently canceled for weather and only bookable within 30 days of departure — treat it as a bonus, not a plan to build a trip around. From Mestia, Ushguli is a separate rough-road leg: roughly 45 km that has been substantially rebuilt with asphalt and concrete in recent years, but the final few kilometers before Ushguli were still unfinished gravel as of the last check, and conditions can turn a 2.5-3 hour drive into much longer after rain or snow. A 4x4 or high-clearance vehicle is still the safe choice, especially outside peak summer.',
  base_towns    = 'Mestia is the only realistic base — it has the guesthouses, restaurants, and the ropeway and museum infrastructure, and every place in this catalog outside Ushguli is a manageable day trip from here. Most visitors day-trip Ushguli from Mestia rather than overnighting, though a single night in an Ushguli guesthouse lets you see the towers in empty early-morning light before the day''s 4x4 convoys arrive.'
WHERE id = 'svaneti';

INSERT INTO catalog_places (
  id, region_id, name, hook, description, tips, best_time,
  duration_min, time_needed, price_gel_min, price_gel_max, price_lari,
  nearest_town, lat, lng, kid_note, booking_required, tags, sort_order,
  guide_script, guide_script_words
) VALUES
  ('svaneti-mestia-old-town', 'svaneti', 'Mestia Old Town & Svan Towers', 'Cobbled lanes and stone defensive towers rising straight out of a working mountain town.', 'Wander the compact center around Seti Square, where 19th- and 20th-century wooden guesthouses sit beside centuries-old Svan defensive towers, all backed by the peaks ringing the valley. Most towers are still attached to private homes, so this is a street-level wander rather than a checklist of interiors — the point is the overall texture of a living mountain town rather than any single monument. Gear shops, bakeries, and cafes line the square if you need last-minute hiking supplies before heading further out. It''s the natural first stop to get oriented before tackling the region''s longer day trips.', 'Free to wander. Most towers are private homes — admire from the street unless a sign or guesthouse explicitly invites you in.', 'Late afternoon or early evening, once the day''s 4x4 convoys have returned', 60, '1 hr', NULL, NULL, 'Free', 'Mestia', 43.0459, 42.7281, 'Flat, easy walking with towers to spot and count — good for a low-key first evening after a long travel day.', false, ARRAY['scenic', 'walk']::TEXT[], 1, NULL, NULL),
  ('svaneti-cafe-laila', 'svaneti', 'Café Laila', 'One of Mestia''s oldest cafés, still turning out honest khinkali and khachapuri with occasional live singing.', 'Café Laila has been a fixture on Seti Square since long before Mestia was a tourist hub, and it''s kept its reputation for solid, unpretentious Georgian food — khinkali, khachapuri, kubdari (the local spiced-meat pie), and hearty soups. The room has a warm, funky, well-worn atmosphere, and reviews mention a Georgian choir performing some evenings, though this isn''t a fixed schedule. It draws a mix of guides, locals, and travelers rather than feeling purely tourist-oriented. It''s an easy walk from anywhere in the old town, making it a natural anchor for a Mestia evening.', 'Cash only. Kitchen service can slow considerably at peak dinner hours, with some visitors reporting close to an hour''s wait — order early or come slightly off-peak. Menu prices weren''t independently confirmed; budget roughly ₾25-45 per person and check the posted menu on arrival. The ₾25-45 a head is an estimate from reviews rather than a published menu — check prices when you order.', 'Dinner — live Georgian singing sometimes happens in the evening, though it''s not scheduled or guaranteed', 90, '1.5 hr', 25, 45, '₾25-45', 'Mestia', 43.0455, 42.7288, 'Big shareable Georgian plates and a relaxed, noisy room — fine for restless kids.', false, ARRAY['wine', 'evening']::TEXT[], 2, NULL, NULL),
  ('svaneti-margiani-house', 'svaneti', 'Margiani House-Museum', 'Climb inside a real medieval Svan defensive tower that most day-trippers walk straight past.', 'Tucked in the Lanchvali quarter above central Mestia, this preserved family residential complex pairs an 11th-century dwelling with a 10th-century defensive tower you can actually climb, floor by floor, up steep interior ladders to the roof. It''s one of the few Svan towers in the region set up for visitors to enter rather than just photograph from outside, and the family who maintains it can walk you through how these tower-houses functioned — livestock below, living quarters above, a fortified retreat on top. The climb itself, on narrow wooden ladders through low openings, is part of the experience. From the roof you get a genuine sense of why every old Svan family wanted one of these.', 'About a 10-minute uphill walk from the central square on a steep cobbled street — not stroller-friendly. Cash only; closed Mondays.', NULL, 60, '1 hr', 10, 10, '₾10', 'Mestia', 43.0425, 42.7268, 'The steep climb inside on narrow wooden ladders is exciting for older kids but tricky for toddlers.', false, ARRAY['scenic']::TEXT[], 3, NULL, NULL),
  ('svaneti-museum', 'svaneti', 'Svaneti History & Ethnography Museum', 'Icons, medieval armor, and a 1,700-year-old Svan weaving loom — the region''s best bad-weather fallback.', 'This branch of the Georgian National Museum on Ioseliani Street holds over 4,000 items pulled from Svaneti''s churches and villages: painted and engraved icons, weapons and armor, silverware, textiles, and an extraordinary ancient wooden loom. It''s a genuinely indoor, all-weather option in a region with very few of them, and gives useful context for the towers and churches you''ll see everywhere else. Displays are modest in scale but dense — expect to read rather than just glance. Guided tours are available if you want more depth than the labels provide.', 'Open 10:00-18:00 daily except Monday. Reported adult admission runs ₾7-10 depending on the source — confirm at the door; a guided tour costs roughly ₾10 extra.', 'Rainy days, or the hottest hour of a summer afternoon', 60, '1 hr', 7, 10, '₾7-10', 'Mestia', 43.0463, 42.7269, NULL, false, ARRAY['cool']::TEXT[], 4, NULL, NULL),
  ('svaneti-zuruldi-ropeway', 'svaneti', 'Zuruldi Ropeway (Hatsvali)', 'A two-stage cable car straight out of Mestia to a 2,347m ridge with a full Caucasus panorama.', 'This two-stage cable car climbs from a lower station on the edge of Mestia, over the Hatsvali ski slopes, to a cafe and viewpoint on the Zuruldi ridge at 2,347m, with Ushba and Tetnuldi visible across the valley on a clear day. It doubles as a ski lift for the Hatsvali resort in winter, but for most of the year it''s a scenery-only ride. The top station has a cafe if you want to linger over the view rather than just snap a photo and head back down. It''s the easiest big-mountain panorama in the region — no hiking required.', 'A return ticket covers both stages. Operating dates and hours vary by season and aren''t fully reliable — in 2026 it opened later than usual (August 8) — so confirm it''s running before building a day around it.', 'Clear mornings, before afternoon cloud builds over the peaks', 120, '2 hr', 25, 25, '₾25 return (both stages)', 'Mestia', 43.039217, 42.729943, 'An easy, exciting way for kids to get a real mountain view without a hike.', false, ARRAY['scenic', 'kids']::TEXT[], 5, NULL, NULL),
  ('svaneti-chalaadi-glacier', 'svaneti', 'Chalaadi Glacier Trail', 'A forest walk to a glacier tongue you can get close to, with no technical gear or experience needed.', 'A dirt road runs about 9-10 km from Mestia to a suspension bridge over the Mestiachala river; from there it''s roughly 3 km (40-60 minutes) each way on a shaded forest trail alongside the glacial meltwater to the Chalaadi glacier''s snout. It''s one of the most accessible glaciers in the Caucasus — a clear, well-trodden path with no ropes or scrambling — but it is a half-day outing once you add the drive to the trailhead. The glacier ice and surrounding moraine are worth the walk even for non-hikers, and the forest keeps most of the route shaded and cool.', 'Reach the trailhead by taxi, rental car, or on foot/bike from town (walking or cycling from Mestia adds roughly 2 hours each way). A taxi to the bridge runs roughly ₾30-40 each way. Wear real shoes — the ground near the ice is loose moraine rock.', 'Morning, for the clearest light and coolest walking temperature', 180, '3 hr', NULL, NULL, 'Free', 'Mestia', 43.117124, 42.696214, 'Manageable for kids around 7-8 and up in proper hiking shoes; too far and rocky for strollers or very young children.', false, ARRAY['hike', 'cool', 'scenic']::TEXT[], 6, NULL, NULL),
  ('svaneti-koruldi-lakes', 'svaneti', 'Koruldi Lakes', 'Alpine lakes at 2,700m below a jagged wall of peaks, reachable only by rough 4x4 track or a serious hike.', 'High above Mestia, the Koruldi Lakes sit at roughly 2,700m with an open panorama of the Svaneti peaks behind them. Most visitors reach them by hired 4x4 up a rough jeep track, followed by a short walk to the shore; committed hikers can also walk the whole way up from Mestia, which turns this into a genuinely long day. Either way, this is not a quick stop — the track alone takes real time and jolts hard in places, and weather at this altitude can close in fast. The reward is one of the best ridge-and-lake panoramas accessible without a multi-day trek.', 'Treat this as a half-day-to-full-day undertaking, not a quick stop, even with the 4x4 option. A shared 4x4 seat runs roughly ₾60 per person; a private vehicle round trip is more like ₾150-250, and prices are negotiable with drivers in Mestia. June-September only — the track is exposed and can close after storms.', 'June-September only; start early to be down before afternoon cloud and storms build at altitude', 300, '5 hr', 60, 250, '₾60-250', 'Mestia', 43.0877, 42.7033, 'The rough 4x4 track is long and jolting — better suited to older kids than toddlers or anyone prone to carsickness.', false, ARRAY['hike', 'scenic']::TEXT[], 7, NULL, NULL),
  ('svaneti-mazeri-ushba', 'svaneti', 'Mazeri & the Ushba Glacier Viewpoint', 'A quieter village with an up-close view of Ushba, the ''Matterhorn of the Caucasus,'' that most itineraries skip.', 'Mazeri is a small village about 15 km from Mestia in the Becho valley, sitting almost directly beneath the twin-peaked Ushba massif. From the village, a trail climbs through pine forest and alpine meadow along the Dolra river; after roughly 1-1.5 hours you reach a viewpoint over Georgia''s tallest waterfall (Shdugra) with Ushba and its glacier filling the skyline. The full route continues much further to the glacier itself, but that''s a strenuous 8-9 hour round trip for serious trekkers only — the viewpoint is where a day-tripper should turn back. It''s one of the best mountain views in the region and sees a fraction of Ushguli''s traffic.', 'Stop at the 1-1.5 hr (each way) viewpoint rather than pushing on to the glacier, which needs real trekking fitness and a full day. Taxi from Mestia runs roughly ₾160-200 return; a normal car can also make the drive.', 'June-September; clouds tend to roll in over Ushba by early afternoon', 270, '4.5 hr', NULL, NULL, 'Free', 'Mazeri', 43.074806, 42.610306, 'The walk to the viewpoint suits older, fit kids; the extension to the glacier itself is not a kids'' hike.', false, ARRAY['hike', 'scenic']::TEXT[], 8, NULL, NULL),
  ('svaneti-ushguli-chazhashi', 'svaneti', 'Ushguli & Chazhashi Tower Village', 'One of Europe''s highest inhabited settlements, its UNESCO-listed core still bristling with medieval towers.', 'Ushguli is a cluster of four hamlets at around 2,100m, and Chazhashi — its best-preserved hamlet and the part actually inscribed by UNESCO — is where the tower-and-house skyline is most dramatic. Wander the stone lanes between towers that have stood since the 9th-13th centuries, with Shkhara''s snowfields visible up the valley on a clear day. This is the region''s single unmissable stop, but it''s also a genuine commitment given the drive from Mestia, so most visitors pair it with Lamaria Church and the Ethnographic Museum on the same day. The setting under Shkhara is as much the draw as any individual building.', 'Most towers are private homes — don''t assume you can walk in; see the Ushguli Ethnographic Museum listing for an interior you can actually visit. Effectively a summer-only destination: the road is difficult or closed roughly outside June-October, and Ushguli itself can be snowbound in winter.', 'Morning, before the day''s 4x4 convoys from Mestia arrive', 90, '1.5 hr', NULL, NULL, 'Free', 'Ushguli', 42.915, 43.00861, 'Uneven cobbled lanes and open irrigation channels between the towers — keep an eye on younger kids.', false, ARRAY['scenic', 'walk']::TEXT[], 9, NULL, NULL),
  ('svaneti-lamaria', 'svaneti', 'Lamaria Church & Shkhara Viewpoint', 'A 9th-century hilltop church above Ushguli framed against Georgia''s highest peak.', 'On the northern edge of Zhibiani, one of Ushguli''s four hamlets, this small Georgian Orthodox church dates to roughly the 9th-10th century and is still an active place of worship. A short climb from the village brings you to the churchyard, from where Shkhara (5,193m, Georgia''s highest point) fills the skyline when the clouds cooperate. It''s a quick add-on to an Ushguli visit rather than a destination in its own right, but the view is one of the best in the region. Modest dress is expected, as at any working Georgian church.', 'Modest dress expected. Shkhara is frequently in cloud — a clear view is a matter of timing and luck, not something to count on.', 'Golden hour, for the best light on Shkhara when it''s visible', 45, '45 min', NULL, NULL, 'Free', 'Ushguli', 42.918354, 43.019656, NULL, false, ARRAY['scenic', 'walk']::TEXT[], 10, NULL, NULL),
  ('svaneti-shkhara-viewpoint', 'svaneti', 'Shkhara Glacier Valley Hike', 'A 16km round-trip valley walk, or horseback ride, to a close-up view of Georgia''s highest peak and its glacier.', 'From Ushguli, a trail follows the open floor of the Enguri valley past grazing horses and cattle toward the base of Shkhara, ending at a viewpoint with the glacier and Shkhara''s ice wall directly ahead. On foot it''s about 16 km round trip and a genuine 5-6 hour commitment; hiring a horse and local guide in Ushguli covers the same ground faster, in roughly 4-5 hours, and is the more popular option for anyone not up for a full day''s walk. Either way there''s no technical difficulty, just distance and exposure — flat valley walking with big views rather than climbing.', 'The walk starts in Ushguli and follows the Enguri valley east towards the glacier, so there is no single trailhead to aim for — head upstream from the village. On foot this is a real 5-6 hour round trip — bring water, sun protection, and sturdy shoes; there''s no shade in the valley. Horses can be hired in Ushguli, typically around ₾70 per horse plus a roughly ₾200 guide fee shared across the group — confirm current rates locally, as they aren''t fixed.', 'June-September only; start by 8am to be back before afternoon weather closes in', 330, '5.5 hr', NULL, NULL, 'Free', 'Ushguli', NULL, NULL, 'Too long and exposed for young kids on foot; older kids may manage it on a hired horse with a guide.', false, ARRAY['hike', 'scenic', 'thrill']::TEXT[], 11, NULL, NULL),
  ('svaneti-ushguli-museum', 'svaneti', 'Ushguli Ethnographic Museum', 'A 13th-century stone machubi packed with Svan looms, cradles, and centuries of household tools.', 'This small museum occupies a machubi, a traditional multi-story Svan stone house, with livestock quarters on the ground floor and family living space above — a hands-on look at how Ushguli households actually functioned for centuries. Highlights include a Svan cradle, an old hearth and bread oven, a stone cellar, and a loom said to be around 1,700 years old. It''s compact but a good complement to wandering Chazhashi''s exteriors, giving you an interior to actually step inside. It also works as Ushguli''s own fallback if the weather turns while you''re there.', 'Cash only. Hours are locally run and can be inconsistent — don''t count on a late-afternoon visit; ask at your guesthouse or in the village for the current opening pattern.', NULL, 30, '30 min', 10, 10, '₾10', 'Ushguli', 42.9145, 43.0095, NULL, false, ARRAY['cool']::TEXT[], 12, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Expect 12.
SELECT count(*) AS svaneti_places
  FROM catalog_places WHERE region_id = 'svaneti';
