"""Generate supabase/migration-00-bootstrap-all.sql.

Faithful ordered concatenation of schema.sql + migration-01..09, with the
only non-idempotent statements in the set wrapped so the whole file is safe
to run against an empty OR a partially-migrated database.

Transformations applied (and nothing else):
  T1  Unguarded `ALTER PUBLICATION supabase_realtime ADD TABLE x;` at column 0
      -> wrapped in a DO block trapping duplicate_object.
      Only column-0 matches are rewritten; migrations 05 and 09 already wrap
      theirs (indented / inline in an existing DO block) and are left alone.
  T2  Unguarded `CREATE POLICY "Allow all for anon" ON x ...;` at column 0
      -> preceded by `DROP POLICY IF EXISTS`. Skipped when the previous
      non-blank line is already the matching DROP (migration-05 has them).
"""

import io
import os
import re

SRC = r"C:\Aadit\Personal\code-ide\vs-code\trip\supabase"
OUT = os.path.join(SRC, "migration-00-bootstrap-all.sql")

ORDER = [
    ("schema.sql", "Base schema: core tables, legacy seed data"),
    ("migration-01-experiences-realtime.sql", "Realtime for experiences"),
    ("migration-02-road-trip-places.sql", "Svaneti + road-trip places (legacy seed)"),
    ("migration-03-itinerary.sql", "Itinerary calendar"),
    ("migration-04-calendar-access.sql", "Calendar edit-access overrides"),
    ("migration-05-notes.sql", "Place + trip notes"),
    ("migration-06-multitenancy.sql", "Multi-tenancy, auth, RLS  <-- the big one"),
    ("migration-07-phase4.sql", "FK fixes, account deletion, moderation"),
    ("migration-08-rls-workaround-rpcs.sql", "SECURITY DEFINER write RPCs"),
    ("migration-09-georgia-catalog.sql", "Georgia catalog tables + seeding RPCs"),
]

PUB = re.compile(r"^ALTER PUBLICATION supabase_realtime ADD TABLE (\w+);\s*$")
POL = re.compile(r'^CREATE POLICY "([^"]+)" ON (\w+)\b')

t1 = t2 = 0


def transform(text):
    global t1, t2
    out = []
    for line in text.split("\n"):
        m = PUB.match(line)
        if m:
            t1 += 1
            out.append(
                "DO $bootstrap$ BEGIN ALTER PUBLICATION supabase_realtime "
                f"ADD TABLE {m.group(1)}; "
                "EXCEPTION WHEN duplicate_object THEN NULL; END $bootstrap$;"
                "  -- bootstrap: guarded"
            )
            continue
        m = POL.match(line)
        if m:
            name, table = m.group(1), m.group(2)
            prev = ""
            for cand in reversed(out):
                if cand.strip():
                    prev = cand.strip()
                    break
            already = prev.startswith(f'DROP POLICY IF EXISTS "{name}" ON {table}')
            if not already:
                t2 += 1
                out.append(
                    f'DROP POLICY IF EXISTS "{name}" ON {table};  -- bootstrap: guarded'
                )
        out.append(line)
    return "\n".join(out)


HEADER = """\
-- ============================================================================
-- migration-00-bootstrap-all.sql
-- Georgia Trip Planner - COMPLETE database bootstrap, safe to run ONCE on a
-- database in ANY state: empty, partially migrated, or fully up to date.
--
-- WHY THIS FILE EXISTS
--   The project's history is schema.sql followed by migration-01..09, each
--   meant to be run in order. If you don't know which ones ran (or you ran
--   them out of order and hit "relation ... does not exist"), running them
--   one at a time is guesswork. This file is all ten, in the correct order,
--   in one paste.
--
-- HOW TO RUN
--   Supabase Dashboard > SQL Editor > New query > paste this whole file >
--   Run. It executes as a single transaction: if anything fails, NOTHING is
--   applied and you are left exactly where you started. Re-running it after
--   a success is a no-op.
--
-- WHAT IT DOES NOT DO
--   It never drops a table, never deletes a row, and never truncates. The
--   only DROPs are `DROP POLICY IF EXISTS` and `DROP CONSTRAINT IF EXISTS`
--   immediately followed by the CREATE/ADD that replaces them - that is the
--   idempotency mechanism, not data loss. Existing data is preserved.
--
-- HOW IT WAS BUILT
--   Generated by concatenating, in order:
--     schema.sql, migration-01 .. migration-09
--   with exactly two mechanical changes, each marked inline with the comment
--   `-- bootstrap: guarded`:
--     * {T1} unguarded `ALTER PUBLICATION ... ADD TABLE x` statements wrapped
--       in a DO block trapping duplicate_object (ADD TABLE has no IF NOT
--       EXISTS form, so a second run would otherwise abort).
--     * {T2} unguarded `CREATE POLICY` statements preceded by
--       `DROP POLICY IF EXISTS` (CREATE POLICY has no OR REPLACE).
--   Nothing else was edited, reordered, or removed. Migrations 05-09 were
--   already fully idempotent and are byte-identical to their source files.
--
-- A NOTE ON THE LEGACY SEED DATA
--   schema.sql and migration-02 insert the original single-trip data (8
--   users, 8 regions, ~57 experiences) with no trip_id. After migration-06
--   the app scopes every read by trip_id, so these rows are invisible to it
--   - harmless history, not live content. They do NOT collide with the
--   Georgia catalog: migration-09 seeds per-trip rows with ids of the form
--   `<slug>-<trip_uuid>`, a different key space entirely.
--
-- AFTER RUNNING
--   Run the verification block at the very bottom of this file.
-- ============================================================================

"""

parts = [HEADER]
for fname, desc in ORDER:
    with io.open(os.path.join(SRC, fname), encoding="utf-8") as fh:
        body = transform(fh.read())
    bar = "=" * 76
    parts.append(
        f"\n\n-- {bar}\n"
        f"-- SOURCE FILE: {fname}\n"
        f"-- {desc}\n"
        f"-- {bar}\n\n{body}"
    )

FOOTER = """


-- BOOTSTRAP-FOOTER-SENTINEL
-- ============================================================================
-- VERIFICATION - safe to re-run any time, reads only.
--
-- Everything above has already run by this point. This block reports what
-- actually landed. Read the `status` column: every row should say OK.
-- ============================================================================

WITH expected_tables(t) AS (
  VALUES ('users'),('regions'),('experiences'),('votes'),('ratings'),('comments'),
         ('itinerary_items'),('calendar_access'),('place_notes'),('trip_notes'),
         ('profiles'),('trips'),('trip_members'),('trip_invites'),
         ('comment_reports'),('blocked_members'),('catalog_regions'),('catalog_places')
),
missing_tables AS (
  SELECT string_agg(t, ', ' ORDER BY t) AS names, count(*) AS n
  FROM expected_tables e
  WHERE NOT EXISTS (
    SELECT 1 FROM pg_tables p WHERE p.schemaname = 'public' AND p.tablename = e.t
  )
),
rls_off AS (
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname) AS names, count(*) AS n
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN expected_tables e ON e.t = c.relname
  WHERE n.nspname = 'public' AND c.relkind = 'r' AND NOT c.relrowsecurity
),
funcs AS (
  SELECT
    count(*) FILTER (WHERE n.nspname = 'public')  AS pub,
    count(*) FILTER (WHERE n.nspname = 'private') AS priv,
    count(*) FILTER (WHERE NOT p.prosecdef)       AS not_secdef
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname IN ('public', 'private')
    AND p.prokind = 'f'
    AND p.proname IN (
      'handle_new_auth_user','handle_new_trip','redeem_trip_invite','delete_own_account',
      'create_trip','update_own_profile','add_region','add_experience','upsert_vote',
      'upsert_rating','add_comment','delete_comment','add_itinerary_item',
      'update_itinerary_item','delete_itinerary_item','grant_calendar_access',
      'revoke_calendar_access','upsert_place_note','upsert_trip_note','update_member_role',
      'remove_trip_member','report_comment','dismiss_report','block_member','unblock_member',
      'seed_trip_catalog','create_georgia_trip','set_trip_region_selected',
      'is_trip_member','is_trip_admin','my_member_ids'
    )
)
SELECT * FROM (
  SELECT 1 AS ord, 'tables present' AS check,
         '18 of 18' AS expected,
         (18 - (SELECT n FROM missing_tables))::text || ' of 18'
           || COALESCE(' (missing: ' || (SELECT names FROM missing_tables) || ')', '') AS actual,
         CASE WHEN (SELECT n FROM missing_tables) = 0 THEN 'OK' ELSE 'FAIL' END AS status
  UNION ALL
  SELECT 2, 'RLS enabled on every table', 'all',
         CASE WHEN (SELECT n FROM rls_off) = 0 THEN 'all'
              ELSE 'RLS OFF on: ' || (SELECT names FROM rls_off) END,
         CASE WHEN (SELECT n FROM rls_off) = 0 THEN 'OK' ELSE 'FAIL' END
  UNION ALL
  SELECT 3, 'public RPCs', '28', (SELECT pub FROM funcs)::text,
         CASE WHEN (SELECT pub FROM funcs) = 28 THEN 'OK' ELSE 'FAIL' END
  UNION ALL
  SELECT 4, 'private helper functions', '3', (SELECT priv FROM funcs)::text,
         CASE WHEN (SELECT priv FROM funcs) = 3 THEN 'OK' ELSE 'FAIL' END
  UNION ALL
  SELECT 5, 'all of them SECURITY DEFINER', '0 plain',
         (SELECT not_secdef FROM funcs)::text || ' plain',
         CASE WHEN (SELECT not_secdef FROM funcs) = 0 THEN 'OK' ELSE 'FAIL' END
  UNION ALL
  SELECT 6, 'realtime publication', '>= 9 tables',
         (SELECT count(*)::text FROM pg_publication_tables WHERE pubname = 'supabase_realtime'),
         CASE WHEN (SELECT count(*) FROM pg_publication_tables
                    WHERE pubname = 'supabase_realtime') >= 9 THEN 'OK' ELSE 'CHECK' END
  UNION ALL
  -- The two partial unique indexes migration-09's own verification omitted.
  SELECT 7, 'catalog partial unique indexes', '2',
         (SELECT count(*)::text FROM pg_indexes WHERE schemaname = 'public'
           AND indexname IN ('regions_trip_catalog_uidx','experiences_trip_catalog_uidx')),
         CASE WHEN (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public'
           AND indexname IN ('regions_trip_catalog_uidx','experiences_trip_catalog_uidx')) = 2
         THEN 'OK' ELSE 'FAIL' END
  UNION ALL
  SELECT 8, 'catalog content loaded', 'run migration-10 files next',
         (SELECT count(*)::text FROM public.catalog_regions) || ' regions, '
           || (SELECT count(*)::text FROM public.catalog_places) || ' places',
         'INFO'
) v ORDER BY ord;
"""

text = "".join(parts) + FOOTER
text = text.replace("{T1}", "T1").replace("{T2}", "T2")

with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(text)

print("wrote", OUT)
print("lines:", text.count("\n") + 1)
print("T1 publication guards:", t1)
print("T2 policy guards:", t2)
